### ISSUE TITLE
Getting segfault on `t2 list` No usb controller found!

### ISSUE THREAD

**Issue by ericuldall** [tessel/t2-cli#1007]
I've tried installing a few times switching between different versions of node with nvm and i'm still getting this same error:

```
t2 list

ERR! WARNING: No usb controller found on this system.
Segmentation fault: 11
```

I added a console log to see the actual error getting thrown:
```
Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/Users/Eric/.nvm/versions/v4.6.0/lib/node_modules/t2-cli/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/Eric/.nvm/versions/v4.6.0/lib/node_modules/t2-cli/node_modules/usb/usb.js:1:119)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

Is there any known fix for this? 

I'm currently running:
Node v4.6.0
NPM 2.15.9
OSX v10.11.5

**Comment by ericuldall** [comment]
Just switched to node v6 and it's working...

**Comment by dbuentello** [comment]
@ericuldall thanks for opening issue & logging output. records like this are good for future debugging purposes

**Comment by tcr** [comment]
@ericuldall I'll add a fix to ensure this doesn't happen in the future. Thanks for filing.
