### ISSUE TITLE
Ble-ble113a doesn't work

### ISSUE THREAD

**Issue by StudentESE** [tessel/t2-cli#1010]
`t2 run index.js`
> INFO Looking for your Tessel...
INFO Connected to first.
INFO Building project.
INFO Writing project to RAM on first (149.504 kB)...
INFO Deployed.
INFO Running index.js...
events.js:141
      throw er; // Unhandled 'error' event
      ^

> Error: Unable to connect to module.
    at Error (native)
    at e.<anonymous> (/tmp/remote-script/node_modules/ble-ble113a/lib/messenger.js:1:524)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```
var tessel = require('tessel');
var blelib = require('ble-ble113a');

var ble = blelib.use(tessel.port['B']);

ble.on('ready', function(err) {
  console.log('Scanning...');
  ble.startScanning();
});

ble.on('discover', function(peripheral) {
  console.log("Discovered peripheral!", peripheral.toString());
});
```

**Comment by StudentESE** [comment]
Problem fixed itself by removing RFID-Module, changing Port to A, run ...
After plugin things same conditions as error comes up, it also works now ...
