### ISSUE TITLE
reconbot tessel 2

### ISSUE THREAD

**Issue by sjromp** [tessel/t2-cli#1133]
so im running a tessel 2 off a windows 10 64x and whenever i try to establish a lan connection to begin running the bot, i get a huge error. ive included all my steps up to the prolem in question, and have run through all the step in the initial tessel 2 set up and the reconbot setup up to actually running the 
t2 run  index.js 
section where it crashes.
Steven@Alcibiades MINGW64 ~/j5ik/j5ik-reconbot-tessel-edition-master
$ dir
app                index.js    lib        package.json
bots-eye-view.png  install.js  motors.js  readme.md

Steven@Alcibiades MINGW64 ~/j5ik/j5ik-reconbot-tessel-edition-master
$ node -v
v6.9.4

Steven@Alcibiades MINGW64 ~/j5ik/j5ik-reconbot-tessel-edition-master
$ npm -v
3.10.10

Steven@Alcibiades MINGW64 ~/j5ik/j5ik-reconbot-tessel-edition-master
$ t2 version
INFO Looking for your Tessel...
INFO Connected to mobile-eye.
INFO Tessel Environment Versions:
INFO t2-cli: 0.1.3
INFO t2-firmware: 0.0.16
INFO Node.js: 4.5.0

Steven@Alcibiades MINGW64 ~/j5ik/j5ik-reconbot-tessel-edition-master
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to mobile-eye.
INFO Building project.
INFO Writing project to RAM on mobile-eye (62.976 kB)...
INFO Deployed.
INFO Running index.js...
ERR! Detected CLI crash TypeError: process.stdin.setRawMode is not a function
ERR!     at Object.exportables.postRun (C:\Users\Steven\AppData\Roaming\npm\node_modules\t2-cli\lib\tessel\deployment\javascript.js:79:19)
ERR!     at tessel.connection.exec (C:\Users\Steven\AppData\Roaming\npm\node_modules\t2-cli\lib\tessel\deploy.js:400:18)
ERR!     at C:\Users\Steven\AppData\Roaming\npm\node_modules\t2-cli\lib\lan-connection.js:94:12
ERR!     at C:\Users\Steven\AppData\Roaming\npm\node_modules\t2-cli\node_modules\ssh2\lib\client.js:1251:5
ERR!     at SSH2Stream.<anonymous> (C:\Users\Steven\AppData\Roaming\npm\node_modules\t2-cli\node_modules\ssh2\lib\Channel.js:177:24)
ERR!     at emitNone (events.js:86:13)
ERR!     at SSH2Stream.emit (events.js:185:7)
ERR!     at parsePacket (C:\Users\Steven\AppData\Roaming\npm\node_modules\t2-cli\node_modules\ssh2-streams\lib\ssh.js:3213:10)
ERR!     at SSH2Stream._transform (C:\Users\Steven\AppData\Roaming\npm\node_modules\t2-cli\node_modules\ssh2-streams\lib\ssh.js:551:13)
ERR!     at SSH2Stream.Transform._read (_stream_transform.js:167:10) TypeError: process.stdin.setRawMode is not a function
ERR!     at Object.exportables.postRun (C:\Users\Steven\AppData\Roaming\npm\node_modules\t2-cli\lib\tessel\deployment\javascript.js:79:19)
ERR!     at tessel.connection.exec (C:\Users\Steven\AppData\Roaming\npm\node_modules\t2-cli\lib\tessel\deploy.js:400:18)
ERR!     at C:\Users\Steven\AppData\Roaming\npm\node_modules\t2-cli\lib\lan-connection.js:94:12
ERR!     at C:\Users\Steven\AppData\Roaming\npm\node_modules\t2-cli\node_modules\ssh2\lib\client.js:1251:5
ERR!     at SSH2Stream.<anonymous> (C:\Users\Steven\AppData\Roaming\npm\node_modules\t2-cli\node_modules\ssh2\lib\Channel.js:177:24)
ERR!     at emitNone (events.js:86:13)
ERR!     at SSH2Stream.emit (events.js:185:7)
ERR!     at parsePacket (C:\Users\Steven\AppData\Roaming\npm\node_modules\t2-cli\node_modules\ssh2-streams\lib\ssh.js:3213:10)
ERR!     at SSH2Stream._transform (C:\Users\Steven\AppData\Roaming\npm\node_modules\t2-cli\node_modules\ssh2-streams\lib\ssh.js:551:13)
ERR!     at SSH2Stream.Transform._read (_stream_transform.js:167:10)
INFO Crash Reported: http://crash-reporter.tessel.io/crashes?fingerprint=0xc6169ae

i'm lost as to what to do. can anyone help?

**Comment by HipsterBrown** [comment]
@sjromp What terminal are you using on Windows?

**Comment by sjromp** [comment]
Github bash

**Comment by HipsterBrown** [comment]
Ok, have you tried running the program from `cmd`?

**Comment by rwaldron** [comment]
Thanks @HipsterBrown 

@sjromp did you start this project from the repo or did you reach it via the Sparkfun guide? There is an accompanying guide that walks through all of the steps here: https://learn.sparkfun.com/tutorials/reconbot-with-the-tessel-2

**Comment by sjromp** [comment]
I was following it through the spark fun website actually, starting with the tessel 2 setup, and then the tessel 2 reconbot setup after the initial setup. I can't yet, (working) but I'll try running it through cmd next afterwards.

**Comment by rwaldron** [comment]
The following are just a collection of relevant issues I've found while researching this issue. 

- https://github.com/senecajs/seneca-in-practice/issues/13
- https://github.com/substack/terminal-menu/issues/25
- https://github.com/AndiDittrich/NodeMCU-Tool/issues/23
- https://github.com/nodejs/node/issues/3006 (it gets most interesting and relevant here: https://github.com/nodejs/node/issues/3006#issuecomment-142438170)
