### ISSUE TITLE
NPM install

### ISSUE THREAD

**Issue by chandanid** [tessel/t2-cli#1192]
I am not able to run npm-install it stops in between.
The debug file is like:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'qunitjs' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData qunitjs
8 silly fetchNamedPackageData qunitjs
9 silly mapToRegistry name qunitjs
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'qunitjs',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'qunitjs',
12 silly mapToRegistry   name: 'qunitjs',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/qunitjs
14 verbose request uri https://registry.npmjs.org/qunitjs
15 verbose request no auth needed
16 info attempt registry request try #1 at 2:02:01 PM
17 verbose request id a95f8d40982b6774
18 verbose etag W/"58f578da-da70"
19 verbose lastModified Tue, 18 Apr 2017 02:24:26 GMT
20 http request GET https://registry.npmjs.org/qunitjs
21 http 304 https://registry.npmjs.org/qunitjs
22 verbose headers { date: 'Fri, 21 Apr 2017 08:32:02 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"58f578da-da70"',
22 verbose headers   age: '185',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-lhr6338-LHR',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '3',
22 verbose headers   'x-timer': 'S1492763523.940666,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Fri, 21 Apr 2017 08:32:02 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"58f578da-da70"',
23 silly get     age: '185',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-lhr6338-LHR',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '3',
23 silly get     'x-timer': 'S1492763523.940666,VS0,VE0',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/qunitjs from cache
25 verbose get saving qunitjs to C:\Users\chandanid\AppData\Roaming\npm-cache\registry.npmjs.org\qunitjs\.cache.json
26 verbose correctMkdir C:\Users\chandanid\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly resolveWithNewModule qunitjs@2.3.2 checking installable status
40 silly cache add args [ 'qunitjs', null ]
41 verbose cache add spec qunitjs
42 silly cache add parsed spec Result {
42 silly cache add   raw: 'qunitjs',
42 silly cache add   scope: null,
42 silly cache add   escapedName: 'qunitjs',
42 silly cache add   name: 'qunitjs',
42 silly cache add   rawSpec: '',
42 silly cache add   spec: 'latest',
42 silly cache add   type: 'tag' }
43 silly addNamed qunitjs@latest
44 verbose addNamed "latest" is being treated as a dist-tag for qunitjs
45 info addNameTag [ 'qunitjs', 'latest' ]
46 silly mapToRegistry name qunitjs
47 silly mapToRegistry using default registry
48 silly mapToRegistry registry https://registry.npmjs.org/
49 silly mapToRegistry data Result {
49 silly mapToRegistry   raw: 'qunitjs',
49 silly mapToRegistry   scope: null,
49 silly mapToRegistry   escapedName: 'qunitjs',
49 silly mapToRegistry   name: 'qunitjs',
49 silly mapToRegistry   rawSpec: '',
49 silly mapToRegistry   spec: 'latest',
49 silly mapToRegistry   type: 'tag' }
50 silly mapToRegistry uri https://registry.npmjs.org/qunitjs
51 verbose addNameTag registry:https://registry.npmjs.org/qunitjs not in flight; fetching
52 verbose get https://registry.npmjs.org/qunitjs not expired, no request
53 silly addNameTag next cb for qunitjs with tag latest
54 silly addNamed qunitjs@2.3.2
55 verbose addNamed "2.3.2" is a plain semver version for qunitjs
56 silly mapToRegistry name qunitjs
57 silly mapToRegistry using default registry
58 silly mapToRegistry registry https://registry.npmjs.org/
59 silly mapToRegistry data Result {
59 silly mapToRegistry   raw: 'qunitjs',
59 silly mapToRegistry   scope: null,
59 silly mapToRegistry   escapedName: 'qunitjs',
59 silly mapToRegistry   name: 'qunitjs',
59 silly mapToRegistry   rawSpec: '',
59 silly mapToRegistry   spec: 'latest',
59 silly mapToRegistry   type: 'tag' }
60 silly mapToRegistry uri https://registry.npmjs.org/qunitjs
61 verbose addRemoteTarball https://registry.npmjs.org/qunitjs/-/qunitjs-2.3.2.tgz not in flight; adding
62 verbose addRemoteTarball [ 'https://registry.npmjs.org/qunitjs/-/qunitjs-2.3.2.tgz',
62 verbose addRemoteTarball   '938ce24250aa3717b90b47598f1429b10343d85a' ]
63 verbose stack Error: kill ENOSYS
63 verbose stack     at exports._errnoException (util.js:1018:11)
63 verbose stack     at process.kill (internal/process.js:190:13)
63 verbose stack     at process.listener (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:86:15)
63 verbose stack     at emitNone (events.js:91:20)
63 verbose stack     at process.emit (events.js:185:7)
63 verbose stack     at processEmit (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
63 verbose stack     at processEmit (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
63 verbose stack     at Signal.wrap.onsignal (internal/process.js:217:44)
64 verbose cwd C:\Program Files
65 error Windows_NT 6.3.9600
66 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "qunitjs"
67 error node v6.10.2
68 error npm  v3.10.10
69 error code ENOSYS
70 error errno ENOSYS
71 error syscall kill
72 error kill ENOSYS
73 error If you need help, you may report this error at:
73 error     <https://github.com/npm/npm/issues>
74 verbose exit [ 1, true ]
```
 Help me out

**Comment by HipsterBrown** [comment]
@chandanid Based on the log, it appears to be an issue with installing [QUnit](https://github.com/qunitjs/qunit) on your machine when running `npm install -g qunitjs`. I would suggest posting an issue in [their repo](https://github.com/qunitjs/qunit) with this log and details about your operating system and node/npm versions.

**Comment by rwaldron** [comment]
Thanks @HipsterBrown
