### ISSUE TITLE
t2 list: "Unhandled rejection TypeError: Cannot set property 'initError' of undefined"

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#123]
```
$ t2 list
INFO Scanning for connections...
Unhandled rejection TypeError: Cannot set property 'initError' of undefined
    at /Users/rwaldron/clonez/t2-cli/lib/usb_connection.js:179:22
    at tryCatcher (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
INFO LAN CONNECTION ip:  192.168.1.14 , name:  wheres-waldron , Authorized:  true
```

I will address this

**Comment by johnnyman727** [comment]
Fixed with #151.
