### ISSUE TITLE
Cannot use @google-cloud/speech on Tessel 2: Pre-compiled module is missing: grpc@1.4.1

### ISSUE THREAD

**Issue by nmqanh** [tessel/t2-cli#1269]
I got following errors when trying to run a project that needs @google-cloud/speech

```
INFO Tessel Environment Versions:
INFO t2-cli: 0.1.5
INFO t2-firmware: 0.1.0
INFO Node.js: 6.10.3
```

```bash
INFO Looking for your Tessel...
INFO Connected to Tessel-AnhNguyen.
INFO Building project.
WARN Pre-compiled module is missing: grpc@1.4.1.
WARN Please an file issue at https://github.com/tessel/t2-cli/issues/new with this warning.
WARN
WARN This warning might be caused by one of the following:
WARN
WARN 1. A pre-compiled binary has not yet been built for this module.
WARN 2. The binary didn't compile correctly for the platform that you're developing on.
WARN    Binaries that are Linux-only or even OpenWRT-specific may cause this issue.
WARN    Try to npm install --force the affected module, then rerun your deployment command.
WARN 3. The binary may be platform specific and impossible to compile for OpenWRT.
INFO Writing project to RAM on Tessel-AnhNguyen (2355.712 kB)...
INFO Deployed.
INFO Running index.js...
module.js:471
    throw err;
    ^

Error: Cannot find module '/tmp/remote-script/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/remote-script/node_modules/grpc/src/node/src/grpc_extension.js:1:205)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by rwaldron** [comment]
Cross-compiled `grpc@1.4.1` and uploaded to server

![](https://i.gyazo.com/cf28a0efd5e566af68422942b2a0861b.png)
