### ISSUE TITLE
node-usb 1.3.2 does not compile

### ISSUE THREAD

**Issue by StudentESE** [tessel/t2-cli#1489]
Related to issue https://github.com/tessel/node-usb/issues/248
nvm 10.5,10.4 9.11.0
MacOS 10.13.4

t2 version:
```
INFO Looking for your Tessel...
INFO Connected to Third.
INFO Tessel Environment Versions:
INFO t2-cli: 0.1.18
INFO t2-firmware: 0.1.0
INFO Node.js: 6.10.3
```
anyone can reproduce this behavior ?

```
'use strict';

// Import the interface to Tessel hardware
const tessel = require('tessel');
var usb = require('usb')
usb.getDeviceList();
```

```
$ t2 run index.js 
INFO Looking for your Tessel...
INFO Connected to Third.
INFO Building project.
WARN Pre-compiled module is missing: usb@1.3.2.
WARN Please an file issue at https://github.com/tessel/t2-cli/issues/new with this warning.
WARN 
WARN This warning might be caused by one of the following:
WARN 
WARN 1. A pre-compiled binary has not yet been built for this module.
WARN 2. The binary didn't compile correctly for the platform that you're developing on.
WARN    Binaries that are Linux-only or even OpenWRT-specific may cause this issue.
WARN    Try to npm install --force the affected module, then rerun your deployment command.
WARN 3. The binary may be platform specific and impossible to compile for OpenWRT.
INFO Writing project to RAM on Third (364.544 kB)...
INFO Deployed.
INFO Running index.js...
module.js:471
    throw err;
    ^

Error: Cannot find module '/tmp/remote-script/node_modules/usb/src/binding/usb_bindings.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/remote-script/node_modules/usb/usb.js:1:452)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by HipsterBrown** [comment]
@StudentESE I was able to compile `usb@1.3.2`. Your sample project should work now. Let me know if you run into any other issues.
