### ISSUE TITLE
Serialport fails on node-usb

### ISSUE THREAD

**Issue by StudentESE** [tessel/t2-cli#1490]
Related to issues:
- https://github.com/tessel/node-usb/issues/248
- https://github.com/tessel/t2-cli/issues/1489

nvm 10.5,10.4 9.11.0
MacOS 10.13.4

t2 version:
```
INFO Looking for your Tessel...
INFO Connected to Third.
INFO Tessel Environment Versions:
INFO t2-cli: 0.1.18
INFO t2-firmware: 0.1.0
INFO Node.js: 6.10.3
```
anyone can reproduce this behavior ?

```
'use strict';

// Import the interface to Tessel hardware
const tessel = require('tessel');
var serialPort = require("serialport");
```

```
t2 run index.js 
INFO Looking for your Tessel...
INFO Connected to Third.
INFO Building project.
WARN Pre-compiled module is missing: usb@1.3.2.
WARN Please an file issue at https://github.com/tessel/t2-cli/issues/new with this warning.
WARN 
WARN This warning might be caused by one of the following:
WARN 
WARN 1. A pre-compiled binary has not yet been built for this module.
WARN 2. The binary didn't compile correctly for the platform that you're developing on.
WARN    Binaries that are Linux-only or even OpenWRT-specific may cause this issue.
WARN    Try to npm install --force the affected module, then rerun your deployment command.
WARN 3. The binary may be platform specific and impossible to compile for OpenWRT.
INFO Writing project to RAM on Third (171.008 kB)...
INFO Deployed.
INFO Running index.js...
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at dirname (path.js:1324:5)
    at Function.exports.getRoot (/tmp/remote-script/node_modules/serialport/node_modules/bindings/bindings.js:1:1834)
    at exports (/tmp/remote-script/node_modules/serialport/node_modules/bindings/bindings.js:1:1000)
    at Object.<anonymous> (/tmp/remote-script/node_modules/serialport/lib/bindings/linux.js:1:103)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by StudentESE** [comment]
Due to the finding `~/.tessel/binaries/` contained serialport-6.2.0-Release-node-**v48**-linux-mipsel.tgz ... I got the idea to downgrade tessel to a version using node v4.8 ...

```
INFO Looking for your Tessel...
INFO Connected to Third.
INFO Tessel Environment Versions:
INFO t2-cli: 0.1.18
INFO t2-firmware: 0.0.16
INFO Node.js: 4.5.0
```
Node 4.5 vs 4.8 ...

but also bad result:

```
t2 run index.js 
INFO Looking for your Tessel...
INFO Connected to Third.
INFO Building project.
WARN Pre-compiled module is missing: serialport@6.2.0.
WARN Please an file issue at https://github.com/tessel/t2-cli/issues/new with this warning.
WARN 
WARN This warning might be caused by one of the following:
WARN 
WARN 1. A pre-compiled binary has not yet been built for this module.
WARN 2. The binary didn't compile correctly for the platform that you're developing on.
WARN    Binaries that are Linux-only or even OpenWRT-specific may cause this issue.
WARN    Try to npm install --force the affected module, then rerun your deployment command.
WARN 3. The binary may be platform specific and impossible to compile for OpenWRT.
INFO Writing project to RAM on Third (89.088 kB)...
INFO Deployed.
INFO Running index.js...
/tmp/remote-script/node_modules/serialport/node_modules/bindings/bindings.js:1
(function (exports, require, module, __filename, __dirname) { var e=require("fs"),r=require("path"),o=r.join,n=r.dirname,t=e.accessSync&&function(r){try{e.accessSync(r)}catch(e){return!1}return!0}||e.existsSync||r.existsSync,i={arrow:process.env.NODE_BINDINGS_ARROW||" → ",compiled:process.env.NODE_BINDINGS_COMPILED_DIR||"compiled",platform:process.platform,arch:process.arch,version:process.versions.node,bindings:"bindings.node",try:[["module_root","build","bindings"],["module_root","build","Debug","bindings"],["module_root","build","Release","bindings"],["module_root","out","Debug","bindings"],["module_root","Debug","bindings"],["module_root","out","Release","bindings"],["module_root","Release","bindings"],["module_root","build","default","bindings"],["module_root","compiled","version","platform","arch","bindings"]]};module.exports=exports=function(e){"string"==typeof e?e={bindings:e}:e||(e={}),Object.keys(i).map(function(r){r 

Error: Could not find module root given file: "undefined". Do you have a `package.json` file? 
    at Function.exports.getRoot (/tmp/remote-script/node_modules/serialport/node_modules/bindings/bindings.js:1:1943)
    at module.exports.exports (/tmp/remote-script/node_modules/serialport/node_modules/bindings/bindings.js:1:1000)
    at Object.<anonymous> (/tmp/remote-script/node_modules/serialport/lib/bindings/linux.js:1:103)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/remote-script/node_modules/serialport/lib/bindings/auto-detect.js:1:370)
```

**Comment by StudentESE** [comment]
Does anyone know a working version combination of tessel version and given Serialport version ?

**Comment by StudentESE** [comment]
setting Node Version to Tessel Node Version (v4.5.0 of 0.0.16) didn't work ... also within t2-compiler (because it switches by itself to v6.5.0 (npm v6.1.0)... 

@rwaldron  Any Idea what I can try further ... ?

**Comment by HipsterBrown** [comment]
@StudentESE I've compiled `usb@1.3.2` so you're program should work now. Please let me know if you're still running into issues. It will only work on node 6, as that is our current compile target.
