### ISSUE TITLE
firebase v5 not working with Tessel 2

### ISSUE THREAD

**Issue by ethangodt** [tessel/t2-cli#1496]
After adding `"firebase": "^5.2.0",` as a dependency I'm getting this error on `t2 run ...`:

```
node-pre-gyp INFO Looking for your Tessel...
node-pre-gyp INFO Connected to peethasaur.
node-pre-gyp INFO Building project.
node-pre-gyp WARN Pre-compiled module is missing: grpc@1.11.3.
node-pre-gyp WARN Please an file issue at https://github.com/tessel/t2-cli/issues/new with this warning.
node-pre-gyp WARN
node-pre-gyp WARN This warning might be caused by one of the following:
node-pre-gyp WARN
node-pre-gyp WARN 1. A pre-compiled binary has not yet been built for this module.
node-pre-gyp WARN 2. The binary didn't compile correctly for the platform that you're developing on.
node-pre-gyp WARN    Binaries that are Linux-only or even OpenWRT-specific may cause this issue.
node-pre-gyp WARN    Try to npm install --force the affected module, then rerun your deployment command.
node-pre-gyp WARN 3. The binary may be platform specific and impossible to compile for OpenWRT.
node-pre-gyp INFO Writing project to RAM on peethasaur (1757.696 kB)...
node-pre-gyp INFO Deployed.
node-pre-gyp INFO Running index.js...
/tmp/remote-script/node_modules/firebase/node_modules/grpc/src/grpc_extension.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";var e,r=require("node-pre-gyp/lib/pre-binding"),n=require("path"),i=r.find(n.resolve(n.join(__dirname,"../package.json")));try{e=require(i)}catch(e){let r,o=require("fs"),t=n.dirname(n.dirname(i)),a=n.basename(n.dirname(i));try{r=o.readdirSync(t)}catch(r){let n=Error(`The gRPC binary module was not installed. This may be fixed by running "npm rebuild"\nOriginal error: ${e.message}`);throw n.code=e.code,n}if(-1===r.indexOf(a)){let n=Error(`Failed to load gRPC binary module because it was not installed for the current system\nExpected directory: ${a}\nFound: [${r.join(", ")}]\nThis problem can often be fixed by running "npm rebuild" on the current system\nOriginal error: ${e.message}`);throw n.code=e.code,n}throw e}module.exports=e;


Error: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"
Original error: Cannot find module '/tmp/remote-script/node_modules/firebase/node_modules/grpc/src/node/extension_binary/node-v48-linux-mipsel-unknown/grpc_node.node'
    at Error (native)
    at Object.<anonymous> (/tmp/remote-script/node_modules/firebase/node_modules/grpc/src/grpc_extension.js:1:338)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/remote-script/node_modules/firebase/node_modules/grpc/src/client_interceptors.js:1:1514)
```

**Comment by ethangodt** [comment]
It looks like there is [some](https://www.youtube.com/watch?v=x5yfkE0lXnA) [stuff](https://twitter.com/tesselproject/status/574007888345063424) online suggesting that using firebase with Tessel 2 is possible, but it's all older and the API looks like it's changed a lot. Is this still supported?

**Comment by HipsterBrown** [comment]
@ethangodt It looks like the native bindings for `grpc@1.11.3` have not been pre-compiled. I'll do that now and let you know.

**Comment by HipsterBrown** [comment]
@ethangodt So I'm having some trouble compiling newer versions of the `grpc` package, the latest version of `firebase` we can support is 4.10.0 until someone figures out how to compiles `grpc@1.11.3`.

**Comment by rwaldron** [comment]
@HipsterBrown confirmed: gprc@1.11.3 fails to compile with our toolchain.
