### ISSUE TITLE
Consistently erroring out during t2 update

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#1566]
I'm running  through my stash of workshop T2s to get them all up to date, which means I'm working from a fresh install of the latest LTS Node, fresh install of t2-cli etc.

Each update appears to run smoothly until a CLI crash in the firmware update (which should be submitted through the usual crash reporter). It looks like this:

```sh
➜  ~ t2 update
INFO Looking for your Tessel...
INFO Connected to bananaStand.
INFO New firmware version found... 0.2.0
INFO Updating bananaStand to latest version (0.2.0)...
INFO Downloading files...
INFO Download complete!
INFO Updating OpenWRT (1/2)
INFO Transferring image of size 16.78 MB. This will take 2-4 minutes...
INFO Transfer complete.
INFO Starting OpenWRT update.
INFO Please do not remove power from Tessel.
INFO This process will take at least 2 minutes...
INFO Configuration is saved during update.
INFO Updating firmware (2/2)
ERR! Detected CLI crash { Error: LIBUSB_ERROR_NOT_FOUND
ERR!     at Device.get (/usr/local/lib/node_modules/t2-cli/node_modules/usb/usb.js:54:67)
ERR!     at Device.usb.Device.open (/usr/local/lib/node_modules/t2-cli/node_modules/usb/usb.js:41:17)
ERR!     at new DFU (/usr/local/lib/node_modules/t2-cli/lib/dfu.js:26:15)
ERR!     at /usr/local/lib/node_modules/t2-cli/lib/usb-connection.js:303:19
ERR!     at new Promise (<anonymous>)
ERR!     at Promise.then.then.then.then (/usr/local/lib/node_modules/t2-cli/lib/usb-connection.js:301:14) errno: -5 } Error: LIBUSB_ERROR_NOT_FOUND
ERR!     at Device.get (/usr/local/lib/node_modules/t2-cli/node_modules/usb/usb.js:54:67)
ERR!     at Device.usb.Device.open (/usr/local/lib/node_modules/t2-cli/node_modules/usb/usb.js:41:17)
ERR!     at new DFU (/usr/local/lib/node_modules/t2-cli/lib/dfu.js:26:15)
ERR!     at /usr/local/lib/node_modules/t2-cli/lib/usb-connection.js:303:19
ERR!     at new Promise (<anonymous>)
ERR!     at Promise.then.then.then.then (/usr/local/lib/node_modules/t2-cli/lib/usb-connection.js:301:14)
INFO Crash Reported: http://crash-reporter.tessel.io/crashes?fingerprint=-0x12ca3d8c4417e093
```

If I CTRL+C out and try running `t2 update`again, I get this error:

```sh
➜  ~ t2 update
INFO Looking for your Tessel...
ERR! Detected CLI crash TypeError: Cannot read property 'bInterfaceNumber' of undefined
ERR!     at Interface.__refresh (/usr/local/lib/node_modules/t2-cli/node_modules/usb/usb.js:176:41)
ERR!     at Device.<anonymous> (/usr/local/lib/node_modules/t2-cli/node_modules/usb/usb.js:242:9) TypeError: Cannot read property 'bInterfaceNumber' of undefined
ERR!     at Interface.__refresh (/usr/local/lib/node_modules/t2-cli/node_modules/usb/usb.js:176:41)
ERR!     at Device.<anonymous> (/usr/local/lib/node_modules/t2-cli/node_modules/usb/usb.js:242:9)
INFO Crash Reported: http://crash-reporter.tessel.io/crashes?fingerprint=-0x40ea44510705dacf
```

If I unplug the device, let it boot up, and run `t2 update` again, it says it's already on the latest:

```sh
➜  ~ t2 update
INFO Looking for your Tessel...
INFO Connected to buggy.
WARN buggy is already on the latest firmware version (0.2.0). You can force an update with "t2 update --force".
```

The errors are very consistent.

I suspect this is related to CLI's trouble handling the reboot phase of firmware update– it happens while the blue LED is breathing.

**Comment by Frijol** [comment]
Whoa! It completed successfully on only one of the boards. This was a board I ran `t2 restore` on first. Related?

```sh
➜  ~ t2 update
INFO Looking for your Tessel...
INFO Connected to trickster.
INFO New firmware version found... 0.2.0
INFO Updating trickster to latest version (0.2.0)...
INFO Downloading files...
INFO Download complete!
INFO Updating OpenWRT (1/2)
INFO Transferring image of size 16.78 MB. This will take 2-4 minutes...
INFO Transfer complete.
INFO Starting OpenWRT update.
INFO Please do not remove power from Tessel.
INFO This process will take at least 2 minutes...
INFO Configuration is saved during update.
INFO Updating firmware (2/2)
INFO Firmware update complete!
INFO Updated trickster from 0.0.12 to 0.2.0
```

**Comment by taitems** [comment]
This is happening to me too. Only difference from the docs is perhaps that I'm running it under `yarn t2 update` etc so I don't have to install globally?
