### ISSUE TITLE
provision command hangs if device is already provisioned

### ISSUE THREAD

**Issue by ekolker** [tessel/t2-cli#157]
Shouldn't it just exit?

On kill:
```
eric@eks9u:~/github/t2-cli$ t2 provision
INFO Connecting to Tessel...
INFO Connected over USB.
ERR! [Error: Keys already exist. Refusing to overwrite them.]




^C/home/eric/github/t2-cli/lib/tessel/tessel.js:22
    this.connection.end(function() {
                   ^
TypeError: Cannot read property 'end' of undefined
    at process.endConnection (/home/eric/github/t2-cli/lib/tessel/tessel.js:22:20)
    at process.g (events.js:199:16)
    at process.emit (events.js:104:17)
    at Signal.wrap.onsignal (node.js:655:46)
```

**Comment by johnnyman727** [comment]
Yes it should. Out of curiosity, did you run this command quickly, before
the OS may have booted completely?

**Comment by ekolker** [comment]
I don't remember, but that's not the (sole) cause. I get this after the thing has had plenty of time to boot:

```
eric@eks9u:~/github/yolo-octo-robot/t2$ t2 provision
INFO Connecting to Tessel...
INFO Connected over USB.
ERR! [Error: Keys already exist. Refusing to overwrite them.]
^C/home/eric/github/t2-cli/lib/tessel/tessel.js:22
    this.connection.end(function() {
                   ^
TypeError: Cannot read property 'end' of undefined
    at process.endConnection (/home/eric/github/t2-cli/lib/tessel/tessel.js:22:20)
    at process.g (events.js:199:16)
    at process.emit (events.js:104:17)
    at Signal.wrap.onsignal (node.js:655:46)
```

**Comment by johnnyman727** [comment]
Gotcha well I will check this out and fix it.
