### ISSUE TITLE
t2 provision hangs when key exists, sigint reveals failure

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#158]
```
$ t2 provision
INFO Connecting to Tessel...
INFO Connected over USB.
ERR! [Error: Keys already exist. Refusing to overwrite them.]

^C/Users/rwaldron/clonez/t2-cli/lib/tessel/tessel.js:22
    this.connection.end(function() {
                   ^
TypeError: Cannot read property 'end' of undefined
    at process.endConnection (/Users/rwaldron/clonez/t2-cli/lib/tessel/tessel.js:22:20)
    at process.g (events.js:199:16)
    at process.emit (events.js:104:17)
    at Signal.wrap.onsignal (node.js:655:46)
```

**Comment by rwaldron** [comment]
Duplicate of #157

**Comment by rwaldron** [comment]
(Sorry about that)
