### ISSUE TITLE
'$t2 update' occurs error '

### ISSUE THREAD

**Issue by woosungchu** [tessel/t2-cli#1741]
1. got tessel2 inventer kit yesterday
2. follow this guide [link](https://learn.sparkfun.com/tutorials/experiment-guide-for-the-johnny-five-inventors-kit/hardware-installation-and-setup) 
3. the command '$t2 update' occur error
4. fix by this method [link](https://gist.github.com/tcr/992978a5dbe5bff2e18f495c5c0973c3#file-t2-windows-fix-zip)
5. retry this guide [link](https://learn.sparkfun.com/tutorials/experiment-guide-for-the-johnny-five-inventors-kit/hardware-installation-and-setup) 
6. it occurs error again

```
C:\aProject\j5\j5ik>t2 list
INFO Searching for nearby Tessels...
        USB     Tessel-02A345830105

C:\aProject\j5\j5ik>t2 rename Frank
INFO Looking for your Tessel...
INFO Connected to Tessel-02A345830105.
INFO Renaming Tessel-02A345830105 to Frank
INFO Changed name of device Tessel-02A345830105 to Frank

C:\aProject\j5\j5ik>t2 update
INFO Looking for your Tessel...
INFO Connected to Frank.
INFO New firmware version found... 0.2.0
INFO Updating Frank to latest version (0.2.0)...
INFO Downloading files...
INFO Download complete!
INFO Updating OpenWRT (1/2)
INFO Transferring image of size 16.78 MB. This will take 2-4 minutes...
INFO Transfer complete.
INFO Starting OpenWRT update.
INFO Please do not remove power from Tessel.
INFO This process will take at least 2 minutes...
INFO Configuration is saved during update.
INFO Updating firmware (2/2)
ERR! Detected CLI crash [Error: LIBUSB_TRANSFER_STALL] { errno: 4 } Error: LIBUSB_TRANSFER_STALL
?
Submit Crash Report to help Tessel Developers improve the CLI ?
ERR! Detected CLI crash Error: No device found in bootloader mode. (Y/n) \
ERR!     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:367:19
ERR!     at new Promise (<anonymous>)
ERR!     at USB.Connection._findBootedDeviceBySerialNumber (C:\Users\Administrator\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:351:10)
ERR!     at Timeout.retry [as _onTimeout] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:328:12)
ERR!     at listOnTimeout (internal/timers.js:549:17)
ERR!     at processTimers (internal/timers.js:492:7) Error: No device found in bootloader mode
ERR!     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:367:19
ERR!     at new Promise (<anonymous>)
ERR!     at USB.Connection._findBootedDeviceBySerialNumber (C:\Users\Administrator\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:351:10)
ERR!     at Timeout.retry [as _onTimeout] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:328:12)
ERR!     at listOnTimeout (internal/timers.js:549:17)
ERR!     at processTimers (internal/timers.js:492:7)
?
?
Submit Crash Report to help Tessel Developers improve the CLI ?
    If yes(y), subsequent crashes will be submitted automatically. No
ERR! Error: Polling is not active.

C:\aProject\j5\j5ik>t2 list
INFO Searching for nearby Tessels...
WARN No Tessels Found.

C:\aProject\j5\j5ik>node -v
v12.16.1

C:\aProject\j5\j5ik>systeminfo
host name:             woosungchu
OS name:                 Microsoft Windows 10 Pro
OS version:              10.0.18362 N/A build 18362
```

**Comment by woosungchu** [comment]
Same with this error #1599
'$t2 update' seem doesn't  work in window

if you stuck on this error, try [this](https://gist.github.com/tcr/992978a5dbe5bff2e18f495c5c0973c3#file-t2-windows-fix-zip) and use linux
