### ISSUE TITLE
Test fails on OS X

### ISSUE THREAD

**Issue by LinusU** [tessel/t2-cli#208]
@rwaldron your latest commit 2230b8eb483e66a0a0068fd748d1625fce9032c3 broke the tests for me :(

```text
>> LAN.Connection - connectionType
>> TypeError: Cannot read property 'Connection' of undefined
>> at Object.exports.LAN.Connection.setUp (test/unit/lan_connection.js:13:33)

>> LAN.Scanner - emitterSubclass
>> TypeError: Cannot read property 'Scanner' of undefined
>> at Object.exports.LAN.Scanner.setUp (test/unit/lan_connection.js:32:27)

>> LAN.Scanner - properties
>> TypeError: Cannot read property 'Scanner' of undefined
>> at Object.exports.LAN.Scanner.setUp (test/unit/lan_connection.js:32:27)

>> LAN.Scanner.prototype.start - createBrowser
>> TypeError: Cannot read property 'Scanner' of undefined
>> at Object.exports.LAN.Scanner.prototype.start.setUp (test/unit/lan_connection.js:66:27)

>> LAN.Scanner.prototype.start - readyDiscover
>> TypeError: Cannot read property 'Scanner' of undefined
>> at Object.exports.LAN.Scanner.prototype.start.setUp (test/unit/lan_connection.js:66:27)

>> LAN.Scanner.prototype.start - readyDiscoverThrows
>> TypeError: Cannot read property 'Scanner' of undefined
>> at Object.exports.LAN.Scanner.prototype.start.setUp (test/unit/lan_connection.js:66:27)

>> LAN.Scanner.prototype.start - updateDiscovered
>> TypeError: Cannot read property 'Scanner' of undefined
>> at Object.exports.LAN.Scanner.prototype.start.setUp (test/unit/lan_connection.js:66:27)

>> LAN.Scanner.prototype.start - updateDiscoveredExists
>> TypeError: Cannot read property 'Scanner' of undefined
>> at Object.exports.LAN.Scanner.prototype.start.setUp (test/unit/lan_connection.js:66:27)

>> LAN.Scanner.prototype.start - updateDiscoveredThrows
>> TypeError: Cannot read property 'Scanner' of undefined
>> at Object.exports.LAN.Scanner.prototype.start.setUp (test/unit/lan_connection.js:66:27)
```

Seems like `IS_TEST_ENV` isn't `true`?

**Comment by rwaldron** [comment]
Did those failures appear on master? Here's the current state of master locally: 

```
rwaldron at nova in ~/clonez/t2-cli on master
$ grunt
Running "jshint:all" (jshint) task
>> 32 files lint free.

Running "jscs:all" (jscs) task
>> 32 files without code style errors.

Running "jsbeautifier:all" (jsbeautifier) task
Beautified 32 files, changed 0 files...OK

Running "nodeunit:tests" (nodeunit) task
Testing bin-tessel-2.js.......OK
Testing deploy.js...OK
Testing discover.js.......OK
Testing erase.js..OK
Testing lan_connection.js.........OK
Testing name.js........OK
Testing provision.js.............OK
Testing tessel.js..OK
Testing wifi.js......OK
>> 135 assertions passed (2613ms)

Done, without errors.
```

Travis is also reporting that master is green.

**Comment by LinusU** [comment]
It was on master, which at the time was at 2230b8eb483e66a0a0068fd748d1625fce9032c3.

I have no idea why thought but after checking out another branch and then going back it fixed itself :confused: strange...
