### ISSUE TITLE
t2 run doesn't exit and leaves process hanging around

### ISSUE THREAD

**Issue by LinusU** [tessel/t2-cli#222]
Running scripts with `t2 run` doesn't exit when the script is finished. This forces me to press `ctrl + c` after a while. When I do this it prints `INFO Stopping script...` and then stops the process on my computer. But node is still left running on the device which causes problems if you try to run another scripts.

**index.js**
```javascript
var tessel = require('tessel')

console.log('It works')
```

**`t2 run index.js`**
```text
INFO Connecting to Tessel...
INFO Connected to Tessel-02A3DB18BE3D over LAN
INFO Writing index.js to RAM on Tessel-02A3DB18BE3D (36.352 kB)...
INFO Deployed.
INFO Running index.js...
It works
^CINFO Stopping script...
```

**`ps | grep node` on device**
```text
root@Tessel-02A3DB18BE3D:(unknown)# ps | grep node
 1705 root      1484 S    ash -c node '/tmp/remote-script/tests/test.js'
 1706 root     35404 S    node /tmp/remote-script/tests/test.js
 1716 root      1480 S    grep node
```

**errors on device next time**
```text
sock err { [Error: connect EAGAIN /var/run/tessel/port_a]
  code: 'EAGAIN',
  errno: 'EAGAIN',
  syscall: 'connect',
  address: '/var/run/tessel/port_a' }
sock err { [Error: connect EAGAIN /var/run/tessel/port_b]
  code: 'EAGAIN',
  errno: 'EAGAIN',
  syscall: 'connect',
  address: '/var/run/tessel/port_b' }

Error: Port socket closed
    at Socket.<anonymous> (/usr/lib/node/tessel.js:37:15)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:467:12)
Error: Port socket closed
    at Socket.<anonymous> (/usr/lib/node/tessel.js:37:15)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:467:12)
```

**Comment by rwaldron** [comment]
Confirmed

**Comment by LinusU** [comment]
Just tested without `require('tessel')` and then it works.

Probably something that should be `unref`ed in `tessel.js`...

**Comment by rwaldron** [comment]
Just spit-balling here... Perhaps the sockets should be manually closed?

**Comment by johnnyman727** [comment]
Moving over to the `t2-firmware` repo: https://github.com/tessel/t2-firmware/issues/80
