### ISSUE TITLE
npm WARN installMany 

### ISSUE THREAD

**Issue by IgitDanny** [tessel/t2-cli#240]
The following WARN installMany happens after `npm install` 
```
dan@dan-VirtualBox:~/T2$ cd t2-cli/
dan@dan-VirtualBox:~/T2/t2-cli$ npm install
npm WARN installMany async was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colony-compiler was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colors was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colorsafeconsole was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany debug was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany effess was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany fstream was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany hardware-resolve was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany humanize was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany my-local-ip was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany nomnom was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany structured-clone was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany temp was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany usb was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
 
> tessel@0.3.23 postinstall /home/daniel/t2/t2-cli/node_modules/tessel
> tessel install-drivers || true; tessel trademark || true

module.js:338
    throw err;
          ^
Error: Cannot find module 'node-pre-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/daniel/t2/t2-cli/node_modules/usb/usb.js:1:76)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
TESSEL™ by TECHNICAL MACHINE™
/
> usb@1.0.6 install /home/daniel/t2/t2-cli/node_modules/usb
> node-pre-gyp install --fallback-to-build

make: Verzeichnis »/home/daniel/t2/t2-cli/node_modules/usb/build« wird betreten
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
../libusb/libusb/os/threads_posix.c:24:0: warning: "_GNU_SOURCE" redefined [enabled by default]
 #  define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
  AR(target) Release/obj.target/usb.a
  COPY Release/usb.a
  CXX(target) Release/obj.target/usb_bindings/src/node_usb.o
  CXX(target) Release/obj.target/usb_bindings/src/device.o
  CXX(target) Release/obj.target/usb_bindings/src/transfer.o
  SOLINK_MODULE(target) Release/obj.target/usb_bindings.node
  COPY Release/usb_bindings.node
  COPY /home/daniel/t2/t2-cli/node_modules/usb/src/binding/usb_bindings.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Verzeichnis »/home/daniel/t2/t2-cli/node_modules/usb/build« wird verlassen
usb-daemon-parser@0.0.1 node_modules/usb-daemon-parser
```

**Comment by johnnyman727** [comment]
@IgitDanny can you explain what command you ran to get this output?

**Comment by IgitDanny** [comment]
@johnnyman727 I tried to reproduce this once more after I noticed, I didn't copy everything out of our slack chat. But the WARNings are gone away when cloning and linking from current version. Maybe there is another factor why I cannot reproduce now. But the goal is achieved: I can work ;-)
