### ISSUE TITLE
npm install on ubuntu 14.04 within virutalbox 

### ISSUE THREAD

**Issue by Student007** [tessel/t2-cli#241]
Installing on a plain new ubuntu 14.04 and node v0.12.7 (NO nvm !!) within virutalbox the usb fallback-to-build by node-pre-gyp doesn't work also after sudo apt-get install gyp node-pre-gyp

```
dan@dan-VirtualBox:~/T2$ cd t2-cli/
dan@dan-VirtualBox:~/T2/t2-cli$ npm install
npm WARN installMany async was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colony-compiler was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colors was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colorsafeconsole was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany debug was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany effess was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany fstream was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany hardware-resolve was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany humanize was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany my-local-ip was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany nomnom was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany structured-clone was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany temp was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany usb was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN prefer global grunt-cli@0.1.13 should be installed with -g
 
> tessel@0.3.23 postinstall /home/dan/T2/t2-cli/node_modules/tessel
> tessel install-drivers || true; tessel trademark || true

module.js:338
    throw err;
          ^
Error: Cannot find module 'node-pre-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/dan/T2/t2-cli/node_modules/usb/usb.js:1:76)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
TESSEL™ by TECHNICAL MACHINE™
-
> usb@1.0.6 install /home/dan/T2/t2-cli/node_modules/usb
> node-pre-gyp install --fallback-to-build

make: Entering directory `/home/dan/T2/t2-cli/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
../libusb/libusb/os/threads_posix.c:24:0: warning: "_GNU_SOURCE" redefined [enabled by default]
 #  define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
                     ^
compilation terminated.
make: *** [Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory `/home/dan/T2/t2-cli/node_modules/usb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dan/T2/t2-cli/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "/usr/bin/nodejs" "/home/dan/T2/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/dan/T2/t2-cli/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/dan/T2/t2-cli/node_modules/usb/src/binding"
gyp ERR! cwd /home/dan/T2/t2-cli/node_modules/usb
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /home/dan/T2/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/dan/T2/t2-cli/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/dan/T2/t2-cli/node_modules/usb/src/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/dan/T2/t2-cli/node_modules/usb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 3.16.0-30-generic
node-pre-gyp ERR! command "node" "/home/dan/T2/t2-cli/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/dan/T2/t2-cli/node_modules/usb
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /home/dan/T2/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/dan/T2/t2-cli/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/dan/T2/t2-cli/node_modules/usb/src/binding' (1)
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! usb@1.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the usb@1.0.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the usb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls usb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dan/T2/t2-cli/npm-debug.log
dan@dan-VirtualBox:~/T2/t2-cli$ 
```

**Comment by Student007** [comment]
`sudo apt-get install build-essential libudev-dev usb` put me to the next step... but is is an error anyway :cry: 
```
dan@dan-VirtualBox:~/T2/t2-cli$ npm install
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /home/dan/T2/t2-cli/node_modules/tessel/node_modules/.bin/colony-compiler
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/home/dan/T2/t2-cli/node_modules/tessel/node_modules/.bin/colony-compiler'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/home/dan/T2/t2-cli/node_modules/tessel/node_modules/.bin/colony-compiler']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/dan/T2/t2-cli/node_modules/tessel/node_modules/.bin/colony-compiler' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/home/dan/T2/t2-cli/node_modules/tessel/node_modules/.bin/colony-compiler'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/home/dan/T2/t2-cli/node_modules/tessel/node_modules/.bin/colony-compiler']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/home/dan/T2/t2-cli/node_modules/tessel/node_modules/.bin/colony-compiler' }

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dan/T2/t2-cli/npm-debug.log
dan@dan-VirtualBox:~/T2/t2-cli$ 


```

**Comment by Student007** [comment]
`sudo npm install -g --save-dev` one more step ... 
```
dan@dan-VirtualBox:~/T2/t2-cli$ sudo npm install -g --save-dev
npm WARN installMany async was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colony-compiler was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colors was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colorsafeconsole was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany debug was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany effess was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany fstream was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany hardware-resolve was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany humanize was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany my-local-ip was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany nomnom was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany structured-clone was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany temp was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany usb was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
-
> tessel@0.3.23 postinstall /usr/lib/node_modules/t2-cli/node_modules/tessel
> tessel install-drivers || true; tessel trademark || true

/usr/lib/node_modules/t2-cli/node_modules/usb/node_modules/node-pre-gyp/node_modules/npmlog/log.js:21
});
 ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/t2-cli/node_modules/usb/node_modules/node-pre-gyp/lib/node-pre-gyp.js:15:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
TESSEL™ by TECHNICAL MACHINE™
-
> usb@1.0.6 install /usr/lib/node_modules/t2-cli/node_modules/usb
> node-pre-gyp install --fallback-to-build

make: Entering directory `/usr/lib/node_modules/t2-cli/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
../libusb/libusb/os/threads_posix.c:24:0: warning: "_GNU_SOURCE" redefined [enabled by default]
 #  define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
  AR(target) Release/obj.target/usb.a
  COPY Release/usb.a
  CXX(target) Release/obj.target/usb_bindings/src/node_usb.o
  CXX(target) Release/obj.target/usb_bindings/src/device.o
  CXX(target) Release/obj.target/usb_bindings/src/transfer.o
  SOLINK_MODULE(target) Release/obj.target/usb_bindings.node
  COPY Release/usb_bindings.node
  COPY /usr/lib/node_modules/t2-cli/node_modules/usb/src/binding/usb_bindings.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory `/usr/lib/node_modules/t2-cli/node_modules/usb/build'
/usr/bin/t2 -> /usr/lib/node_modules/t2-cli/bin/tessel-2.js
t2-cli@0.0.1 /usr/lib/node_modules/t2-cli
├── usb-daemon-parser@0.0.1
├── shell-escape@0.2.0
├── keypress@0.2.1
├── envfile@1.0.0
├── sprintf-js@1.0.3
├── colors@1.1.2
├── async@0.9.2
├── osenv@0.1.3 (os-homedir@1.0.1, os-tmpdir@1.0.1)
├── nomnom@1.8.1 (underscore@1.6.0, chalk@0.4.0)
├── ssh-keygen@0.2.1 (underscore@1.4.4)
├── promzard@0.3.0 (read@1.0.6)
├── bluebird@2.9.34
├── fs-extra@0.18.4 (jsonfile@2.2.1, graceful-fs@3.0.8, rimraf@2.4.2)
├── mdns-js@0.3.1 (debug@2.2.0, semver@4.3.6, mdns-js-packet@0.1.10)
├── ssh2@0.4.10 (readable-stream@1.0.33, ssh2-streams@0.0.15)
├── lodash@3.10.0
├── tessel@0.3.23 (colorsafeconsole@0.0.4, my-local-ip@1.0.0, debug@0.8.1, effess@0.0.5, structured-clone@0.2.2, colors@0.6.2, humanize@0.0.9, async@0.2.10, mkdirp@0.3.5, semver@2.3.2, temp@0.6.0, hardware-resolve@0.1.6, nomnom@1.6.2, tar@0.1.20, fstream@0.1.31, request@2.47.0, colony-compiler@1.0.1)
├── npm@2.13.2
└── usb@1.0.6 (nan@1.8.4)
dan@dan-VirtualBox:~/T2/t2-cli$
```

But ....

```
dan@dan-VirtualBox:~/T2/t2-cli$ t2
module.js:338
    throw err;
          ^
Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/t2-cli/lib/usb_connection.js:6:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/t2-cli/lib/discover.js:1:73)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
dan@dan-VirtualBox:~/T2/t2-cli$
```

**Comment by Student007** [comment]
`sudo npm install -g debug` solves the issue
@johnnyman727 close it after dependencies are managed well.
1.) No superuser requirements!
2.) test it with nvm !

**Comment by johnnyman727** [comment]
Thanks @Student007! Closing in favor of #239.
