### ISSUE TITLE
Travis-CI wrapper missing

### ISSUE THREAD

**Issue by Student007** [tessel/t2-cli#242]
travis-cl output:
```
> node-pre-gyp install --fallback-to-build

gyp ERR! UNCAUGHT EXCEPTION 

gyp ERR! stack Error: Cannot find module 'wrappy'

gyp ERR! stack     at Function.Module._resolveFilename (module.js:336:15)

gyp ERR! stack     at Function.Module._load (module.js:278:25)

```

will be fixed by adding wrapper to the dependencies

**Comment by Student007** [comment]
fixed by pull request https://github.com/tessel/t2-cli/pull/243
