### ISSUE TITLE
Aborting t2 list throws assertion error

### ISSUE THREAD

**Issue by LinusU** [tessel/t2-cli#277]
Pressing `ctrl + c` during `t2 list` throws an assertion error.

```text
INFO Searching for nearby Tessels...
	Tessel-02A3DB18BE3D	USB	
	Tessel-02A3DB18BE3D	LAN	
^Cnode.js:262
      if (!x) throw new Error(msg || 'assertion error');
                    ^
Error: assertion error
    at process.assert (node.js:262:21)
    at process.removeListener (node.js:674:9)
    at process.g (events.js:195:10)
    at process.emit (events.js:129:20)
    at Signal.wrap.onsignal (node.js:655:46)
```

**Comment by johnnyman727** [comment]
Yeah, I've seen this a few times but forgot to report it. If I recall correctly, you have to abort at just the right time to make this happen. Not sure what that time is though.

**Comment by johnnyman727** [comment]
@LinusU I can't seem to repro this anymore... can you?

**Comment by LinusU** [comment]
Hmm, nope

**Comment by johnnyman727** [comment]
Okay, closing for now. Thanks for checking!
