### ISSUE TITLE
Aborting Script Deployed over USB Causes USB Daemon Crash

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#335]
After connect to my Tessel over USB, run blinky and control+c out of it:
```
I'm blinking! (Press CTRL + C to stop)
I'm blinking! (Press CTRL + C to stop)
I'm blinking! (Press CTRL + C to stop)
I'm blinking! (Press CTRL + C to stop)
I'm blinking! (Press CTRL + C to stop)
^CINFO Stopping script...
Unhandled rejection TypeError: Cannot read property 'connectionType' of undefined
    at closeThem (/Users/Jon/Work/technical/t2-cli/lib/controller.js:186:32)
    at /Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:187:20
    at /Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:239:13
    at /Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:119:13
    at _arrayEach (/Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:91:13)
    at _forEachOf (/Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:118:9)
    at _each (/Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:83:13)
    at Object.async.forEachOf.async.eachOf (/Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/Users/Jon/Work/technical/t2-cli/node_modules/async/lib/async.js:215:22)
    at /Users/Jon/Work/technical/t2-cli/lib/controller.js:184:11
    at tryCatcher (/Users/Jon/Work/technical/t2-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/Jon/Work/technical/t2-cli/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/Jon/Work/technical/t2-cli/node_modules/bluebird/js/main/promise.js:70:37)
    at Object.controller.closeTesselConnections (/Users/Jon/Work/technical/t2-cli/lib/controller.js:183:10)
    at /Users/Jon/Work/technical/t2-cli/lib/controller.js:384:29
    at runMicrotasksCallback (node.js:337:7)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Error code 9 upon remote process exit for command: node /tmp/remote-script/index.js
    at USBProcess.<anonymous> (/Users/Jon/Work/technical/t2-cli/lib/usb/usb_process.js:58:26)
    at USBProcess.g (events.js:199:16)
    at USBProcess.emit (events.js:107:17)
    at Parser.<anonymous> (/Users/Jon/Work/technical/t2-cli/lib/usb/usb_daemon.js:117:14)
    at Parser.emit (events.js:107:17)
    at Parser._write (/Users/Jon/Work/technical/t2-cli/node_modules/usb-daemon-parser/index.js:152:16)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Parser.Writable.write (_stream_writable.js:217:11)
    at ondata (_stream_readable.js:540:20)
    at emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Readable.push (_stream_readable.js:126:10)
    at InEndpoint.emit (events.js:107:17)
    at Transfer.transferDone (/Users/Jon/Work/technical/t2-cli/node_modules/usb/usb.js:295:9)
➜  t2-demo  DEBUG=discovery,discovery:*,controller t2 list
INFO Searching for nearby Tessels...
  discovery:usb Device found with matching PID and VID +0ms
  discovery:usb Opening device! +3ms
  discovery Connection opened: +24ms undefined of type USB
  discovery Fetching name: +0ms CP5H379VQGVMPGNG0702A18HFX
  discovery:usb Writing USB command: +8ms [ 'uci', 'get', 'system.@system[0].hostname' ]
  discovery:lan Device found: +243ms Harold._tessel._tcp.local
  discovery:lan Device ready: +2s Harold.local
  discovery Connection opened: +2ms Harold.local of type LAN
  discovery Fetching name: +0ms Harold.local
  discovery:lan Writing LAN command: +1ms [ 'uci', 'get', 'system.@system[0].hostname' ]
	Harold	LAN
  discovery Timeout hit! Waiting for pending to finish... +2s
  discovery Done! Stopping. +2ms
```

The first unhandled rejection error is unrelated (I believe) and fixed with #332. 

However, we then see that the process exited with error code 9 (SIGKILL). Just after this happens, the USB Daemon on T2 dies (at least, I can no longer see it running with `ps`) and the call to fetch the name of the device in the subsequent `t2 list` call never returns so only the `LAN` connection is displayed.

That means you can no longer use the USB connection until Tessel is restarted. 

Probably related to #324.

**Comment by johnnyman727** [comment]
So after a fair amount of investigation, it looks like the USB Daemon is freezing sporadically and I have no idea why :fearful:.

Will need to investigate further with fresh eyes.

**Comment by johnnyman727** [comment]
It's even doing weird shit like running through this code:
```.c
    // If this stream has no more data internally or we don't want to flush it
    // close it immediately
    if (pb->bufcount == 0 || flush == NO_FLUSH) {
        // If the file descriptor exists (which it should)
        if (pb->fd != -1) {
            // Close it
            int ret = close(pb->fd);
            debug("We attempted to close the file descriptor %d", ret);
            if (ret == -1) {
                fatal("Unable to close the file descriptor: %s", strerror(errno));
            }
            debug("then got here");
            // Set it back to -1
            pb->fd = -1;
            debug("then here");
            // Reset other fields
            pb->startpos = pb->endpos = pb->bufcount = 0;
            debug("then finally here...");
            // pipebuf_common_debug(pb, "Successfully closed");
            debug("And will return the success");
            return CLOSE_SUCCESS;
        }
```
And only printing:
```
We attempted to close the file descriptor 0
then got here
then here
then finally here...
```
Where is the "And will return the success" output!!!???

**Comment by johnnyman727** [comment]
Okay, I've found the root cause of the overarching problem. I still don't know why the daemon just stops printing the last line but maybe it's a weird buffering issue...

1. When a process is aborted, [the event is captured in `tessel.js` and it tells the USB Connection to close all open processes](https://github.com/tessel/t2-cli/blob/9c4ca6967bea1f410b64d30321fe6f4476208470/lib/tessel/tessel.js#L15-L37).
2. The USB Connection [obliges and begins the process of closing down connections](https://github.com/tessel/t2-cli/blob/9c4ca6967bea1f410b64d30321fe6f4476208470/lib/usb/usb_daemon.js#L50-L58). It does this by [sending the `KILL` signal to each process](https://github.com/tessel/t2-cli/blob/9c4ca6967bea1f410b64d30321fe6f4476208470/lib/usb/usb_daemon.js#L50-L58), waiting for the remote daemon [to tell it that the process was killed](https://github.com/tessel/t2-cli/blob/9c4ca6967bea1f410b64d30321fe6f4476208470/lib/usb/usb_process.js#L34-L49), then [sends the daemon the command to `close` the process](https://github.com/tessel/t2-cli/blob/9c4ca6967bea1f410b64d30321fe6f4476208470/lib/usb/usb_process.js#L42) which essentially cleans up memory and frees up that process ID.
3. Once that completes, `tessel.js` will [exit the process](https://github.com/tessel/t2-cli/blob/9c4ca6967bea1f410b64d30321fe6f4476208470/lib/tessel/tessel.js#L26-L28)

The problem is that once the [`deploy` command resolves](https://github.com/tessel/t2-cli/blob/9c4ca6967bea1f410b64d30321fe6f4476208470/lib/tessel/deploy.js#L279-L285), we attempt to [close the Tessel connection again](https://github.com/tessel/t2-cli/blob/9c4ca6967bea1f410b64d30321fe6f4476208470/lib/controller.js#L381) which is already in the midst of closing from the `SIGINT` handler in `tessel.js` as described above. That [resolves the close process](https://github.com/tessel/t2-cli/blob/9c4ca6967bea1f410b64d30321fe6f4476208470/lib/tessel/tessel.js#L16-L17) pretty much immediately and [returns to the command parser file (`tessel-2.js`)](https://github.com/tessel/t2-cli/blob/9c4ca6967bea1f410b64d30321fe6f4476208470/bin/tessel-2.js#L54) which, since there was no error, [forces the process to close](https://github.com/tessel/t2-cli/blob/9c4ca6967bea1f410b64d30321fe6f4476208470/bin/tessel-2.js#L12). 

However, because the process of killing then closing each process hasn't completed yes, the USB Daemon still reserves that process id (which is usually 0 - the first one). Then, when you try to run another CLI command - the USB Daemon complains that the process with ID 0 already exists and dies. Thus the inability to make another USB command.

The USB Daemon does restart itself after that second failed command though.
