### ISSUE TITLE
If a machine doesn't have `usb` support, an error will be thrown upon process completion

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#397]
```
➜  ~  t2 list
ERR! WARNING: No usb controller found on this system.
INFO Searching for nearby Tessels...
^C/Users/Jon/Work/technical/t2-cli/lib/usb_connection.js:339
  usb.removeAllListeners('attach');
     ^
TypeError: Cannot read property 'removeAllListeners' of undefined
    at USB.Scanner.stop (/Users/Jon/Work/technical/t2-cli/lib/usb_connection.js:339:6)
    at TesselSeeker.stop (/Users/Jon/Work/technical/t2-cli/lib/discover.js:126:18)
    at process.<anonymous> (/Users/Jon/Work/technical/t2-cli/lib/controller.js:108:16)
    at process.g (events.js:199:16)
    at process.emit (events.js:104:17)
    at Signal.wrap.onsignal (node.js:655:46)
```

**Comment by johnnyman727** [comment]
We should just check if `usb` is defined before trying to remove listeners.

**Comment by Frijol** [comment]
I'm getting `ERR! WARNING: No usb controller found on this system.` and don't understand this issue - is this a warning from within t2-cli?

**Comment by rwaldron** [comment]
You need to upgrade to node 4.2.1 or newer and run npm rebuild or just reinstall t2-cli

**Comment by Frijol** [comment]
thanks, fixed!
