### ISSUE TITLE
Can't read version on latest CLI and firmware

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#411]
Pretty sure this is an up-to-date T2

```sh
➜  ~  t2 update
INFO Looking for your Tessel...
INFO Connected to Tessel-02A3589D746E over LAN
Unhandled rejection TypeError: Cannot read property 'version' of undefined
    at /usr/local/lib/node_modules/t2-cli/lib/controller.js:722:52
    at tryCatcher (/usr/local/lib/node_modules/t2-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/t2-cli/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/t2-cli/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/t2-cli/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/local/lib/node_modules/t2-cli/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/t2-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/t2-cli/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
^C^C
➜  ~  t2 version
INFO Looking for your Tessel...
INFO Connected to Tessel-02A3589D746E over LAN
INFO Tessel [Tessel-02A3589D746E] version: unknown
➜  ~
```

**Comment by johnnyman727** [comment]
@Frijol can you get a root shell and check if a `/etc/tessel-version` file exists?

**Comment by Frijol** [comment]
fix: go into dterm or ssh, etc/tessel-version, replace what's there with 1293f03d42ae00b11267e5af2d6739c8cac77165

**Comment by johnnyman727** [comment]
I'll fix this on the build server. In my jet-lagged delerium last night, I forgot to make a new build of openwrt after I merged my version bump into master - so the commit sha that was saved (and how we fetch the version) was of my branch, not master.

**Comment by johnnyman727** [comment]
I fixed this on AWS.
