### ISSUE TITLE
Cannot install t2-cli on arch linux

### ISSUE THREAD

**Issue by RX14** [tessel/t2-cli#414]
```
$ s npm install t2-cli -g
[sudo] password for rx14:
npm WARN engine mdns-js@0.4.0: wanted: {"node":"^0.10.3 || ^0.12.0"} (current: {"node":"4.2.1","npm":"3.3.9"})
/usr/bin/t2 -> /usr/lib/node_modules/t2-cli/bin/tessel-2.js

> usb@1.1.0 install /usr/lib/node_modules/t2-cli/node_modules/usb
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.2.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/t2-cli/node_modules/usb/.node-gyp"
make: Entering directory '/usr/lib/node_modules/t2-cli/node_modules/usb/build'
make: *** No rule to make target '../.node-gyp/4.2.1/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/t2-cli/node_modules/usb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.3-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/t
2-cli/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/usr/lib/node_modules/t2-cli/node_modules/usb/src/binding"
gyp ERR! cwd /usr/lib/node_modules/t2-cli/node_modules/usb
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module
=/usr/lib/node_modules/t2-cli/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/usr/lib/node_modules/t2-cli/node_modules/usb/src/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/t2-cli/node_modules/usb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.2.3-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/t2-cli/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/t2-cli/node_modules/usb
node-pre-gyp ERR! node -v v4.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/t2-cli/n
ode_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/usr/lib/node_modules/t2-cli/node_modules/usb/src/binding' (1)
npm WARN install:usb@1.1.0 usb@1.1.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:usb@1.1.0 Exit status 1
/usr/lib
└── (empty)

npm ERR! code 1
```

**Comment by stevelacy** [comment]
Also received the error using the `udev` bug fixes branch: [jon-fix-linux-install](https://github.com/tessel/t2-cli/tree/jon-fix-linux-install)

OS: Debian 8
Kernel: 4.2.0 AMD64

**Comment by RX14** [comment]
The issue seems to be installing the `usb` npm module, `sudo npm install -g usb` provides the same error, I will open a bug there.

**Comment by willm** [comment]
I'm on the jon-fix-linux-install branch and kernal 3.13.0-52 and it built for me

**Comment by RX14** [comment]
Bug: nonolith/node-usb#98

Seems to be when compiling the usb node module's native code as root. Installing from source may fix?

**Comment by stevelacy** [comment]
Installed `node-usb` from source without improvement.

**Comment by stevelacy** [comment]
Correction, `npm i --ignore-scripts` worked

**Comment by RX14** [comment]
I think that without the native code, the usb module will not work.

**Comment by rwaldron** [comment]
Can someone retry and confirm this? Important to note that Node.js 4.x.x LTS is a _requirement_, not a suggestion.

**Comment by RX14** [comment]
Still fails as root for me

**Comment by johnnyman727** [comment]
@RX14 which version of Node are you running?

@kevinmehall any guesses here?

**Comment by kevinmehall** [comment]
This is https://github.com/nodejs/node-gyp/issues/454

My recommendation is to never run npm as root/sudo, which npm's defaults on Linux make unnecessarily difficult. Follow [these instructions](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md) fix `npm -g` to install under your home directory.

**Comment by rwaldron** [comment]
Closing per @kevinmehall's cited issue

**Comment by allenjwelch** [comment]
Although this issue is closed, in case anyone needs it I also got the same error and was able to install on linux by cloning the repo and using the instructions from the readme (https://github.com/tessel/t2-cli):

**Installation for development**
Prerequisites for installation: Node.js and Git.
    Clone this repository by entering the following: git clone https://github.com/tessel/t2-cli.
    Go to the root directory of repository: cd t2-cli.
    Create a symbolic link: npm link --local.
