### ISSUE TITLE
--slim complains about missing package.json

### ISSUE THREAD

**Issue by AndreSantos** [tessel/t2-cli#417]
I have a directory with accel.js, package.json, node_modules, and several other files. When I deploy with the --slim option, Tessel complains that the package.json is missing:
```
[~/Projects/fullstack2015/tessel]$ DEBUG=discovery,discovery:lan t2 run accel.js --name blip --lan --slim -t 30 
INFO Looking for your Tessel...
  discovery Will scan for LAN devices +0ms
  discovery:lan Device found: +361ms Tessel-02A3D386296B._tessel._tcp.local
  discovery:lan Device found: +10ms WillThisRunMyCar._tessel._tcp.local
  discovery:lan Device found: +4ms skynet._tessel._tcp.local
  discovery:lan Device found: +1ms George._tessel._tcp.local
  discovery:lan Device found: +1ms blip._tessel._tcp.local
  discovery:lan Device found: +1ms supertessel._tessel._tcp.local
  discovery:lan Device open error: +3s supertessel.local
  discovery Kicking supertessel due to authorized filter: true +2ms
  discovery Error opening device +3ms undefined
  discovery:lan Device open error: +13ms WillThisRunMyCar.local
  discovery Kicking WillThisRunMyCar due to authorized filter: true +2ms
  discovery Error opening device +0ms undefined
  discovery:lan Device open error: +12ms Tessel-02A3D386296B.local
  discovery Kicking Tessel-02A3D386296B due to authorized filter: true +1ms
  discovery Error opening device +0ms undefined
  discovery:lan Device open error: +1ms skynet.local
  discovery Kicking skynet due to authorized filter: true +1ms
  discovery Error opening device +0ms undefined
  discovery:lan Device ready: +758ms blip.local
  discovery Connection opened: +1ms blip.local
  discovery Fetching name: +0ms blip.local
INFO Connected to blip over LAN
  discovery:lan Device open error: +525ms George.local
  discovery Kicking George due to authorized filter: true +0ms
  discovery Error opening device +1ms undefined
INFO Generating slim build.
INFO Writing accel.js to RAM on blip (467.968 kB)...
INFO Deployed.
INFO Running build.js...
/tmp/remote-script/build.js:7
}catch(s){r=s}if(n||r)throw n||r;return o}),w.lutimes||(x.hasOwnProperty("O_SYMLINK")?(w.lutimes=function(e,t,n,r){w.open(e,x.O_SYMLINK,function(e,o){return r=r||i,e?r(e):void w.futimes(o,t,n,function(e){w.close(o,function(t){return r(e||t)})})})},w.lutimesSync=function(e,t,n){var r,i,o,s=w.openSync(e,x.O_SYMLINK);try{var o=w.futimesSync(s,t,n)}catch(a){r=a}try{w.closeSync(s)}catch(a){i=a}if(r||i)throw r||i;return o}):w.utimensat&&x.hasOwnProperty("AT_SYMLINK_NOFOLLOW")?(w.lutimes=function(e,t,n,r){w.utimensat(e,t,n,x.AT_SYMLINK_NOFOLLOW,r)},w.lutimesSync=function(e,t,n){return w.utimensatSync(e,t,n,x.AT_SYMLINK_NOFOLLOW)}):(w.lutimes=function(e,t,n,r){process.nextTick(r)},w.lutimesSync=function(){})),w.chown=y(w.chown),w.fchown=y(w.fchown),w.lchown=y(w.lchown),w.chownSync=b(w.chownSync),w.fchownSync=b(w.fchownSync),w.lchownSync=b(w.lchownSync),w.lchmod||(w.lchmod=function(e,t,n){process.nextTick(n)},w.lchmodSync=function(){}),w.lchown||(w.lchown=function(e,t,n,r){process.nextT

Error: package.json does not exist at /tmp/remote-script/package.json
    at Object.n.find (/tmp/remote-script/build.js:7:5246)
    at Object.a.108.events (/tmp/remote-script/build.js:9:759)
    at i (/tmp/remote-script/build.js:1:316)
    at /tmp/remote-script/build.js:1:367
    at Object.a.114.../dfu/dfu (/tmp/remote-script/build.js:9:17298)
    at i (/tmp/remote-script/build.js:1:316)
    at /tmp/remote-script/build.js:1:367
    at Object.a.111../bundle (/tmp/remote-script/build.js:9:14122)
    at i (/tmp/remote-script/build.js:1:316)
    at /tmp/remote-script/build.js:1:367
```

**Comment by rwaldron** [comment]
I'm knee deep in deployment right now, so I'll tackle this along with the rest.

**Comment by HipsterBrown** [comment]
@rwaldron does node need a `package.json` to resolve dependencies located in `node_modules/`?

**Comment by rwaldron** [comment]
@HipsterBrown shouldn't be an issue because all deps are rolled into a single file. 

@AndreSantos need more information here, can you share the source code?

**Comment by HipsterBrown** [comment]
Ah good point. Yea maybe it's a specific dependency then.

**Comment by rwaldron** [comment]
I'm going to close this for now, we can reopen/revisit if the issue appears again.
