### ISSUE TITLE
t2 update: Error: DFU functional descriptor is invalid

### ISSUE THREAD

**Issue by Student007** [tessel/t2-cli#421]
While updating this error causes:
> INFO Beginning update download. This could take a couple minutes..
  downloading [====================] 100% 0.0s remaining
INFO Download complete!
INFO Updating OpenWRT (1/2)
INFO Transferring image of size 20.19 MB
INFO Starting OpenWRT update. Please do not remove power from Tessel.
INFO Updating firwmare (2/2)
Unhandled rejection Error: DFU functional descriptor is invalid
    at new DFU (/Users/{anonym}/.nvm/versions/node/v4.2.1/lib/node_modules/t2-cli/lib/dfu.js:41:15)
    at createDFU (/Users/{anonym}/.nvm/versions/node/v4.2.1/lib/node_modules/t2-cli/lib/usb_connection.js:207:27)
    at tryCatcher (/Users/{anonym}/.nvm/versions/node/v4.2.1/lib/node_modules/t2-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/{anonym}/.nvm/versions/node/v4.2.1/lib/node_modules/t2-cli/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/{anonym}/.nvm/versions/node/v4.2.1/lib/node_modules/t2-cli/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/{anonym}/.nvm/versions/node/v4.2.1/lib/node_modules/t2-cli/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/{anonym}/.nvm/versions/node/v4.2.1/lib/node_modules/t2-cli/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/{anonym}/.nvm/versions/node/v4.2.1/lib/node_modules/t2-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues as _onImmediate (/Users/{anonym}/.nvm/versions/node/v4.2.1/lib/node_modules/t2-cli/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate as _immediateCallback (timers.js:368:17)

**Comment by johnnyman727** [comment]
Thanks for reporting this @Student007! 

@Frijol already reported it [here](https://github.com/tessel/t2-firmware/issues/121) on the firmware repo so I'll close this one for now unless we discover it's definitely a CLI issue.
