### ISSUE TITLE
t2 provision fails on master

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#436]
```
$ t2 provision
Unhandled rejection Error: No key provided to set as default.
    at /Users/rwaldron/clonez/t2-cli/lib/tessel/provision.js:160:21
    at Object.actions.setDefaultKey (/Users/rwaldron/clonez/t2-cli/lib/tessel/provision.js:157:10)
    at Function.Tessel.get (/Users/rwaldron/clonez/t2-cli/lib/controller.js:121:20)
    at /Users/rwaldron/clonez/t2-cli/lib/controller.js:280:19
    at tryCatcher (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/promise.js:70:37)
    at Object.controller.standardTesselCommand (/Users/rwaldron/clonez/t2-cli/lib/controller.js:278:10)
    at executeProvision (/Users/rwaldron/clonez/t2-cli/lib/controller.js:517:25)
    at tryCatcher (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/async.js:15:14)
```

Encountered this while setting up a Tessel after doing a sysupgrade

**Comment by rwaldron** [comment]
Had to do this: 

```
$ t2 provision --key ~/.tessel/id_rsa
INFO Looking for your Tessel...
INFO Connected to bb8 over USB
INFO Authenticating Tessel with public key...
INFO Tessel is already authenticated with this computer.
```

cc @HipsterBrown

**Comment by johnnyman727** [comment]
Damn, must have been a regression with my key branch :/
