### ISSUE TITLE
Installing T2 CLI not working on node v5.0.0

### ISSUE THREAD

**Issue by Drizej** [tessel/t2-cli#439]
When installing the T2 CLI I get a wide assortment of errors. I don't know if it helps, but here is a dump of the errors:
```
npm WARN engine mdns-js@0.4.0: wanted: {"node":"^0.10.3 || ^0.12.0"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm WARN addRemoteGit git+https://github.com/rynomad/jsbn.git resetting remote /Users/andrzej/.npm/_git-remotes/git-https-github-com-rynomad-jsbn-git-5eacfb5ecac35cf3eb2fc8aac95d0469 because of error: Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! git clone --template=/Users/andrzej/.npm/_git-remotes/_templates --mirror https://github.com/rynomad/jsbn.git /Users/andrzej/.npm/_git-remotes/git-https-github-com-rynomad-jsbn-git-5eacfb5ecac35cf3eb2fc8aac95d0469: Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm WARN install Couldn't install optional dependency: Command failed: git clone --template=/Users/andrzej/.npm/_git-remotes/_templates --mirror https://github.com/rynomad/jsbn.git /Users/andrzej/.npm/_git-remotes/git-https-github-com-rynomad-jsbn-git-5eacfb5ecac35cf3eb2fc8aac95d0469
npm WARN install 
npm WARN install 
npm WARN install Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm WARN install 
npm WARN install 
npm WARN install 
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
/usr/local/lib
└─┬ t2-cli@0.0.6 
  ├── async@1.5.0 
  ├── bluebird@2.10.2 
  ├─┬ browserify@11.2.0 
  │ ├── assert@1.3.0 
  │ ├─┬ browser-pack@5.0.1 
  │ │ ├─┬ combine-source-map@0.6.1 
  │ │ │ ├── convert-source-map@1.1.2 
  │ │ │ ├── inline-source-map@0.5.0 
  │ │ │ ├── lodash.memoize@3.0.4 
  │ │ │ └─┬ source-map@0.4.4 
  │ │ │   └── amdefine@1.0.0 
  │ │ └── umd@3.0.1 
  │ ├── browser-resolve@1.10.1 
  │ ├─┬ browserify-zlib@0.1.4 
  │ │ └── pako@0.2.8 
  │ ├─┬ buffer@3.5.2 
  │ │ ├── base64-js@0.0.8 
  │ │ ├── ieee754@1.1.6 
  │ │ └── is-array@1.0.1 
  │ ├── builtins@0.0.7 
  │ ├── commondir@0.0.1 
  │ ├─┬ concat-stream@1.4.10 
  │ │ ├── readable-stream@1.1.13 
  │ │ └── typedarray@0.0.6 
  │ ├─┬ console-browserify@1.1.0 
  │ │ └── date-now@0.1.4 
  │ ├── constants-browserify@0.0.1 
  │ ├─┬ crypto-browserify@3.11.0 
  │ │ ├─┬ browserify-cipher@1.0.0 
  │ │ │ ├─┬ browserify-aes@1.0.5 
  │ │ │ │ └── buffer-xor@1.0.3 
  │ │ │ ├─┬ browserify-des@1.0.0 
  │ │ │ │ └─┬ des.js@1.0.0 
  │ │ │ │   └── minimalistic-assert@1.0.0 
  │ │ │ └── evp_bytestokey@1.0.0 
  │ │ ├─┬ browserify-sign@4.0.0 
  │ │ │ ├── bn.js@4.1.1 
  │ │ │ ├── browserify-rsa@4.0.0 
  │ │ │ ├─┬ elliptic@6.0.2 
  │ │ │ │ ├── brorand@1.0.5 
  │ │ │ │ └── hash.js@1.0.3 
  │ │ │ └─┬ parse-asn1@5.0.0 
  │ │ │   └── asn1.js@4.0.0 
  │ │ ├── create-ecdh@4.0.0 
  │ │ ├─┬ create-hash@1.1.2 
  │ │ │ ├── cipher-base@1.0.2 
  │ │ │ └── ripemd160@1.0.1 
  │ │ ├── create-hmac@1.1.4 
  │ │ ├─┬ diffie-hellman@5.0.0 
  │ │ │ └── miller-rabin@4.0.0 
  │ │ ├── pbkdf2@3.0.4 
  │ │ ├── public-encrypt@4.0.0 
  │ │ └── randombytes@2.0.1 
  │ ├── defined@1.0.0 
  │ ├── deps-sort@1.3.9 
  │ ├── domain-browser@1.1.4 
  │ ├─┬ duplexer2@0.0.2 
  │ │ └── readable-stream@1.1.13 
  │ ├── events@1.0.2 
  │ ├── glob@4.5.3 
  │ ├─┬ has@1.0.1 
  │ │ └── function-bind@1.0.2 
  │ ├── htmlescape@1.1.0 
  │ ├── https-browserify@0.0.1 
  │ ├── inherits@2.0.1 
  │ ├─┬ insert-module-globals@6.6.3 
  │ │ ├── is-buffer@1.1.0 
  │ │ └─┬ lexical-scope@1.2.0 
  │ │   └── astw@2.0.0 
  │ ├── isarray@0.0.1 
  │ ├─┬ JSONStream@1.0.6 
  │ │ └── jsonparse@1.2.0 
  │ ├─┬ labeled-stream-splicer@1.0.2 
  │ │ └─┬ stream-splicer@1.3.2 
  │ │   └── readable-stream@1.1.13 
  │ ├─┬ module-deps@3.9.1 
  │ │ ├── detective@4.3.1 
  │ │ ├── readable-stream@1.1.13 
  │ │ └─┬ stream-combiner2@1.0.2 
  │ │   └─┬ through2@0.5.1 
  │ │     ├── readable-stream@1.0.33 
  │ │     └── xtend@3.0.0 
  │ ├── os-browserify@0.1.2 
  │ ├─┬ parents@1.0.1 
  │ │ └── path-platform@0.11.15 
  │ ├── path-browserify@0.0.0 
  │ ├── process@0.11.2 
  │ ├── punycode@1.3.2 
  │ ├── querystring-es3@0.2.1 
  │ ├─┬ read-only-stream@1.1.1 
  │ │ ├── readable-stream@1.1.13 
  │ │ └─┬ readable-wrap@1.0.0 
  │ │   └── readable-stream@1.1.13 
  │ ├─┬ readable-stream@2.0.4 
  │ │ ├── core-util-is@1.0.1 
  │ │ ├── process-nextick-args@1.0.3 
  │ │ └── util-deprecate@1.0.2 
  │ ├── resolve@1.1.6 
  │ ├─┬ shasum@1.0.2 
  │ │ ├─┬ json-stable-stringify@0.0.1 
  │ │ │ └── jsonify@0.0.0 
  │ │ └── sha.js@2.4.4 
  │ ├── shell-quote@0.0.1 
  │ ├── stream-browserify@2.0.1 
  │ ├─┬ stream-http@1.7.1 
  │ │ ├── builtin-status-codes@1.0.0 
  │ │ ├── foreach@2.0.5 
  │ │ ├── indexof@0.0.1 
  │ │ └── object-keys@1.0.9 
  │ ├── string_decoder@0.10.31 
  │ ├─┬ subarg@1.0.0 
  │ │ └── minimist@1.2.0 
  │ ├─┬ syntax-error@1.1.4 
  │ │ └── acorn@1.2.2 
  │ ├─┬ through2@1.1.1 
  │ │ └── readable-stream@1.1.13 
  │ ├── timers-browserify@1.4.1 
  │ ├── tty-browserify@0.0.0 
  │ ├─┬ url@0.10.3 
  │ │ └── querystring@0.2.0 
  │ ├── util@0.10.3 
  │ ├── vm-browserify@0.0.4 
  │ └── xtend@4.0.1 
  ├── colors@1.1.2 
  ├─┬ debug@2.2.0 
  │ └── ms@0.7.1 
  ├── envfile@1.0.0 
  ├─┬ fs-extra@0.18.4 
  │ ├── graceful-fs@3.0.8 
  │ ├── jsonfile@2.2.3 
  │ └── rimraf@2.4.3 
  ├── fs-temp@1.0.0 
  ├─┬ fstream@1.0.8 
  │ ├── graceful-fs@4.1.2 
  │ └─┬ mkdirp@0.5.1 
  │   └── minimist@0.0.8 
  ├─┬ fstream-ignore@1.0.3 
  │ └─┬ minimatch@3.0.0 
  │   └─┬ brace-expansion@1.1.1 
  │     ├── balanced-match@0.2.1 
  │     └── concat-map@0.0.1 
  ├─┬ glob@5.0.15 
  │ ├─┬ inflight@1.0.4 
  │ │ └── wrappy@1.0.1 
  │ ├── minimatch@2.0.10 
  │ ├── once@1.3.2 
  │ └── path-is-absolute@1.0.0 
  ├─┬ inquirer@0.8.5 
  │ ├── ansi-regex@1.1.1 
  │ ├─┬ chalk@1.1.1 
  │ │ ├── ansi-styles@2.1.0 
  │ │ ├── escape-string-regexp@1.0.3 
  │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ └── ansi-regex@2.0.0 
  │ │ ├─┬ strip-ansi@3.0.0 
  │ │ │ └── ansi-regex@2.0.0 
  │ │ └── supports-color@2.0.0 
  │ ├── cli-width@1.1.0 
  │ ├── figures@1.4.0 
  │ ├─┬ readline2@0.1.1 
  │ │ ├── mute-stream@0.0.4 
  │ │ └── strip-ansi@2.0.1 
  │ ├── rx@2.5.3 
  │ └── through@2.3.8 
  ├── keypress@0.2.1 
  ├── lodash@3.10.1 
  ├─┬ mdns-js@0.4.0 
  │ ├─┬ mdns-js-packet@0.1.12 
  │ │ └── qap@3.1.3 
  │ └── semver@4.3.6 
  ├─┬ node-rsa@0.2.26 
  │ ├── asn1@0.2.3 
  │ └── lodash@3.3.0 
  ├─┬ nomnom@1.8.1 
  │ ├─┬ chalk@0.4.0 
  │ │ ├── ansi-styles@1.0.0 
  │ │ ├── has-color@0.1.7 
  │ │ └── strip-ansi@0.1.1 
  │ └── underscore@1.6.0 
  ├─┬ npm@2.14.11 
  │ ├── ansi-regex@2.0.0 
  │ ├── block-stream@0.0.8 
  │ ├─┬ cmd-shim@2.0.1
  │ │ └── graceful-fs@3.0.8 
  │ ├── fstream@1.0.8 
  │ ├─┬ fstream-npm@1.0.7
  │ │ └── fstream-ignore@1.0.3 
  │ ├─┬ glob@5.0.15 
  │ │ └── path-is-absolute@1.0.0 
  │ ├── graceful-fs@4.1.2 
  │ ├── inflight@1.0.4 
  │ ├── inherits@2.0.1 
  │ ├─┬ init-package-json@1.9.1
  │ │ └── promzard@0.3.0 
  │ ├─┬ minimatch@3.0.0 
  │ │ └─┬ brace-expansion@1.1.1 
  │ │   ├── balanced-match@0.2.1 
  │ │   └── concat-map@0.0.1 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ ├─┬ node-gyp@3.0.3
  │ │ ├─┬ glob@4.5.3 
  │ │ │ └─┬ minimatch@2.0.10 
  │ │ │   └─┬ brace-expansion@1.1.1 
  │ │ │     ├── balanced-match@0.2.1 
  │ │ │     └── concat-map@0.0.1 
  │ │ └─┬ path-array@1.0.0
  │ │   └─┬ array-index@0.1.1
  │ │     └─┬ debug@2.2.0 
  │ │       └── ms@0.7.1 
  │ ├─┬ npm-registry-client@7.0.7
  │ │ └─┬ concat-stream@1.5.0
  │ │   ├─┬ readable-stream@2.0.2
  │ │   │ ├── core-util-is@1.0.1 
  │ │   │ ├── isarray@0.0.1 
  │ │   │ ├── process-nextick-args@1.0.3 
  │ │   │ └── string_decoder@0.10.31 
  │ │   └── typedarray@0.0.6 
  │ ├── once@1.3.2 
  │ ├─┬ osenv@0.1.3 
  │ │ └── os-tmpdir@1.0.1 
  │ ├── read@1.0.7 
  │ ├─┬ readable-stream@1.1.13 
  │ │ ├── core-util-is@1.0.1 
  │ │ ├── isarray@0.0.1 
  │ │ └── string_decoder@0.10.31 
  │ ├─┬ request@2.65.0 
  │ │ ├── aws-sign2@0.6.0 
  │ │ ├─┬ bl@1.0.0 
  │ │ │ └─┬ readable-stream@2.0.3
  │ │ │   ├── core-util-is@1.0.1 
  │ │ │   ├── isarray@0.0.1 
  │ │ │   ├── process-nextick-args@1.0.3 
  │ │ │   ├── string_decoder@0.10.31 
  │ │ │   └── util-deprecate@1.0.2 
  │ │ ├── caseless@0.11.0 
  │ │ ├─┬ combined-stream@1.0.5 
  │ │ │ └── delayed-stream@1.0.0 
  │ │ ├── extend@3.0.0 
  │ │ ├── forever-agent@0.6.1 
  │ │ ├─┬ form-data@1.0.0-rc3 
  │ │ │ └── async@1.5.0 
  │ │ ├─┬ har-validator@2.0.2 
  │ │ │ ├─┬ chalk@1.1.1 
  │ │ │ │ ├── ansi-styles@2.1.0 
  │ │ │ │ ├── escape-string-regexp@1.0.3 
  │ │ │ │ ├── has-ansi@2.0.0 
  │ │ │ │ └── supports-color@2.0.0 
  │ │ │ ├─┬ commander@2.9.0 
  │ │ │ │ └── graceful-readlink@1.0.1 
  │ │ │ ├─┬ is-my-json-valid@2.12.2
  │ │ │ │ ├── generate-function@2.0.0 
  │ │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ │ └── is-property@1.0.2 
  │ │ │ │ └── jsonpointer@2.0.0 
  │ │ │ └─┬ pinkie-promise@1.0.0 
  │ │ │   └── pinkie@1.0.0 
  │ │ ├─┬ hawk@3.1.0
  │ │ │ ├── cryptiles@2.0.5 
  │ │ │ ├── hoek@2.16.3 
  │ │ │ └── sntp@1.0.9 
  │ │ ├─┬ http-signature@0.11.0 
  │ │ │ ├── asn1@0.1.11 
  │ │ │ ├── assert-plus@0.1.5 
  │ │ │ └── ctype@0.5.3 
  │ │ ├── isstream@0.1.2 
  │ │ ├── json-stringify-safe@5.0.1 
  │ │ ├─┬ mime-types@2.1.7 
  │ │ │ └── mime-db@1.19.0 
  │ │ ├── oauth-sign@0.8.0 
  │ │ ├── qs@5.2.0 
  │ │ ├── stringstream@0.0.5 
  │ │ └── tunnel-agent@0.4.1 
  │ ├── rimraf@2.4.3 
  │ ├─┬ sha@2.0.1
  │ │ └─┬ readable-stream@2.0.2
  │ │   ├── core-util-is@1.0.1 
  │ │   ├── isarray@0.0.1 
  │ │   ├── process-nextick-args@1.0.3 
  │ │   └── string_decoder@0.10.31 
  │ ├── strip-ansi@3.0.0 
  │ ├── tar@2.2.1 
  │ ├─┬ validate-npm-package-name@2.2.2
  │ │ └── builtins@0.0.7 
  │ └── wrappy@1.0.1 
  ├─┬ osenv@0.1.3 
  │ ├── os-homedir@1.0.1 
  │ └── os-tmpdir@1.0.1 
  ├── progress@1.1.8 
  ├─┬ promzard@0.3.0 
  │ └── read@1.0.7 
  ├─┬ request@2.65.0 
  │ ├── aws-sign2@0.6.0 
  │ ├── bl@1.0.0 
  │ ├── caseless@0.11.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ ├── extend@3.0.0 
  │ ├── forever-agent@0.6.1 
  │ ├── form-data@1.0.0-rc3 
  │ ├─┬ har-validator@2.0.2 
  │ │ ├─┬ commander@2.9.0 
  │ │ │ └── graceful-readlink@1.0.1 
  │ │ ├─┬ is-my-json-valid@2.12.3 
  │ │ │ ├── generate-function@2.0.0 
  │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ └── is-property@1.0.2 
  │ │ │ └── jsonpointer@2.0.0 
  │ │ └─┬ pinkie-promise@1.0.0 
  │ │   └── pinkie@1.0.0 
  │ ├─┬ hawk@3.1.1 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@0.11.0 
  │ │ ├── asn1@0.1.11 
  │ │ └── ctype@0.5.3 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├─┬ mime-types@2.1.7 
  │ │ └── mime-db@1.19.0 
  │ ├── node-uuid@1.4.7 
  │ ├── oauth-sign@0.8.0 
  │ ├── qs@5.2.0 
  │ ├── stringstream@0.0.5 
  │ ├── tough-cookie@2.2.1 
  │ └── tunnel-agent@0.4.1 
  ├── shell-escape@0.2.0 
  ├── sprintf-js@1.0.3 
  ├─┬ ssh2@0.4.12 
  │ ├── readable-stream@1.0.33 
  │ └─┬ ssh2-streams@0.0.19 
  │   ├── readable-stream@1.0.33 
  │   └── streamsearch@0.1.2 
  ├─┬ sshpk@1.6.2 
  │ ├── assert-plus@0.1.5 
  │ ├── dashdash@1.10.1 
  │ ├── jodid25519@1.0.2 
  │ ├── jsbn@0.1.0 
  │ └── tweetnacl@0.13.2 
  ├─┬ stream-to-buffer@0.1.0 
  │ └── stream-to@0.2.2 
  ├─┬ tar@2.2.1 
  │ └── block-stream@0.0.8 
  ├─┬ tar-stream@1.3.1 
  │ └── end-of-stream@1.1.0 
  ├─┬ uglify-js@2.6.0 
  │ ├── async@0.2.10 
  │ ├── source-map@0.5.3 
  │ ├── uglify-to-browserify@1.0.2 
  │ └─┬ yargs@3.10.0 
  │   ├── camelcase@1.2.1 
  │   ├─┬ cliui@2.1.0 
  │   │ ├─┬ center-align@0.1.2 
  │   │ │ ├─┬ align-text@0.1.3 
  │   │ │ │ ├── kind-of@2.0.1 
  │   │ │ │ ├── longest@1.0.1 
  │   │ │ │ └── repeat-string@1.5.2 
  │   │ │ └── lazy-cache@0.2.4 
  │   │ ├── right-align@0.1.3 
  │   │ └── wordwrap@0.0.2 
  │   ├── decamelize@1.1.1 
  │   └── window-size@0.1.0 
  ├── url-join@0.0.1 
  ├─┬ usb@1.1.0 
  │ ├── nan@2.1.0 
  │ └─┬ node-pre-gyp@0.6.4 (git+https://github.com/mapbox/node-pre-gyp.git#c88d6a0472cf7697af08c2090175e7427e788cb9)
  │   ├─┬ mkdirp@0.5.1 
  │   │ └── minimist@0.0.8 
  │   ├─┬ npmlog@1.1.0
  │   │ └─┬ are-we-there-yet@1.0.4
  │   │   └─┬ readable-stream@1.1.13 
  │   │     ├── core-util-is@1.0.1 
  │   │     ├── inherits@2.0.1 
  │   │     ├── isarray@0.0.1 
  │   │     └── string_decoder@0.10.31 
  │   ├─┬ request@2.65.0 
  │   │ ├── aws-sign2@0.6.0 
  │   │ ├─┬ bl@1.0.0 
  │   │ │ └─┬ readable-stream@2.0.3
  │   │ │   ├── core-util-is@1.0.1 
  │   │ │   ├── inherits@2.0.1 
  │   │ │   ├── isarray@0.0.1 
  │   │ │   ├── process-nextick-args@1.0.3 
  │   │ │   ├── string_decoder@0.10.31 
  │   │ │   └── util-deprecate@1.0.2 
  │   │ ├── caseless@0.11.0 
  │   │ ├─┬ combined-stream@1.0.5 
  │   │ │ └── delayed-stream@1.0.0 
  │   │ ├── extend@3.0.0 
  │   │ ├── forever-agent@0.6.1 
  │   │ ├─┬ form-data@1.0.0-rc3 
  │   │ │ └── async@1.5.0 
  │   │ ├─┬ har-validator@2.0.2 
  │   │ │ ├─┬ chalk@1.1.1 
  │   │ │ │ ├── ansi-styles@2.1.0 
  │   │ │ │ ├── escape-string-regexp@1.0.3 
  │   │ │ │ ├─┬ has-ansi@2.0.0 
  │   │ │ │ │ └── ansi-regex@2.0.0 
  │   │ │ │ ├─┬ strip-ansi@3.0.0 
  │   │ │ │ │ └── ansi-regex@2.0.0 
  │   │ │ │ └── supports-color@2.0.0 
  │   │ │ ├─┬ commander@2.9.0 
  │   │ │ │ └── graceful-readlink@1.0.1 
  │   │ │ ├─┬ is-my-json-valid@2.12.2
  │   │ │ │ ├── generate-function@2.0.0 
  │   │ │ │ ├─┬ generate-object-property@1.2.0 
  │   │ │ │ │ └── is-property@1.0.2 
  │   │ │ │ └── jsonpointer@2.0.0 
  │   │ │ └─┬ pinkie-promise@1.0.0 
  │   │ │   └── pinkie@1.0.0 
  │   │ ├─┬ hawk@3.1.0
  │   │ │ ├── cryptiles@2.0.5 
  │   │ │ ├── hoek@2.16.3 
  │   │ │ └── sntp@1.0.9 
  │   │ ├─┬ http-signature@0.11.0 
  │   │ │ ├── asn1@0.1.11 
  │   │ │ ├── assert-plus@0.1.5 
  │   │ │ └── ctype@0.5.3 
  │   │ ├── isstream@0.1.2 
  │   │ ├── json-stringify-safe@5.0.1 
  │   │ ├─┬ mime-types@2.1.7 
  │   │ │ └── mime-db@1.19.0 
  │   │ ├── oauth-sign@0.8.0 
  │   │ ├── qs@5.2.0 
  │   │ ├── stringstream@0.0.5 
  │   │ └── tunnel-agent@0.4.1 
  │   ├── semver@4.3.6 
  │   ├─┬ tar@1.0.3
  │   │ ├── block-stream@0.0.8 
  │   │ ├─┬ fstream@1.0.8 
  │   │ │ └── graceful-fs@4.1.2 
  │   │ └── inherits@2.0.1 
  │   └─┬ tar-pack@2.0.1
  │     ├─┬ fstream@0.1.31
  │     │ ├── graceful-fs@3.0.8 
  │     │ └── inherits@2.0.1 
  │     ├─┬ fstream-ignore@0.0.7
  │     │ └── inherits@2.0.1 
  │     ├── graceful-fs@4.1.2 
  │     ├─┬ readable-stream@1.0.33 
  │     │ ├── core-util-is@1.0.1 
  │     │ ├── inherits@2.0.1 
  │     │ ├── isarray@0.0.1 
  │     │ └── string_decoder@0.10.31 
  │     └─┬ tar@0.1.20
  │       ├── block-stream@0.0.8 
  │       └── inherits@2.0.1 
  └── usb-daemon-parser@0.0.1 

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "t2-cli"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrzej/npm-debug.log
Andrzejs-MacBook-Pro:~ andrzej$ sudo npm install -g t2-cli
npm WARN engine mdns-js@0.4.0: wanted: {"node":"^0.10.3 || ^0.12.0"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm WARN addRemoteGit git+https://github.com/rynomad/jsbn.git resetting remote /Users/andrzej/.npm/_git-remotes/git-https-github-com-rynomad-jsbn-git-5eacfb5ecac35cf3eb2fc8aac95d0469 because of error: You have not agreed to the Xcode license agreements, please run 'xcodebuild -license' (for user-level acceptance) or 'sudo xcodebuild -license' (for system-wide acceptance) from within a Terminal window to review and agree to the Xcode license agreements.
npm ERR! git clone --template=/Users/andrzej/.npm/_git-remotes/_templates --mirror https://github.com/rynomad/jsbn.git /Users/andrzej/.npm/_git-remotes/git-https-github-com-rynomad-jsbn-git-5eacfb5ecac35cf3eb2fc8aac95d0469: You have not agreed to the Xcode license agreements, please run 'xcodebuild -license' (for user-level acceptance) or 'sudo xcodebuild -license' (for system-wide acceptance) from within a Terminal window to review and agree to the Xcode license agreements.
npm WARN install Couldn't install optional dependency: Command failed: git clone --template=/Users/andrzej/.npm/_git-remotes/_templates --mirror https://github.com/rynomad/jsbn.git /Users/andrzej/.npm/_git-remotes/git-https-github-com-rynomad-jsbn-git-5eacfb5ecac35cf3eb2fc8aac95d0469
npm WARN install 
npm WARN install You have not agreed to the Xcode license agreements, please run 'xcodebuild -license' (for user-level acceptance) or 'sudo xcodebuild -license' (for system-wide acceptance) from within a Terminal window to review and agree to the Xcode license agreements.
npm WARN install 
/usr/local/bin/t2 -> /usr/local/lib/node_modules/t2-cli/bin/tessel-2.js

> usb@1.1.0 install /usr/local/lib/node_modules/t2-cli/node_modules/usb
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/andrzej/.node-gyp/5.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/t2-cli/node_modules/usb/.node-gyp"


Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.





Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.





Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/t2-cli/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/usr/local/lib/node_modules/t2-cli/node_modules/usb/src/binding"
gyp ERR! cwd /usr/local/lib/node_modules/t2-cli/node_modules/usb
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/t2-cli/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/usr/local/lib/node_modules/t2-cli/node_modules/usb/src/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/t2-cli/node_modules/usb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.0.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/t2-cli/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/t2-cli/node_modules/usb
node-pre-gyp ERR! node -v v5.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/t2-cli/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/usr/local/lib/node_modules/t2-cli/node_modules/usb/src/binding' (1)
npm WARN install:usb usb@1.1.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:usb Exit status 1
/usr/local/lib
└── (empty)

npm ERR! code 1
```

**Comment by Drizej** [comment]
Ok, so one of my problems may have been that I had not yet agreed to the XCode license agreement.

**Comment by rwaldron** [comment]
All of these failures are being caused by a brand new installation of Xcode that hasn't had it's license agreed to. Presumably you updated Xcode sometime in the last few days and this is the first time anything you've done has required `sudo`. You can fix that part by typing `sudo ls` (safe), which will prompt you to agree to the license. Once you've done that, try this again.

**Comment by Drizej** [comment]
Thanks.  Yes, after agreeing to the xCode license agreement, the problems are resolved.

**Comment by LinusU** [comment]
Glad you got it resolved :)
