### ISSUE TITLE
Stop using new Error(...) in reject()

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#449]
When `reject(new Error(...))` is called, `closeFailedCommand` (in bin/tessel-2.js) does this: 

```
  if (err instanceof Error) {
    throw err;
  } else {
```

Which means this happens: 

```
Unhandled rejection Error: blah blah blah
```

...Followed by the entire stack trace. 

Passing a string will log the string as a warning.

**Comment by rwaldron** [comment]
Or should it just use `logs.err` when the argument is actually a `new Error()` object?

**Comment by rwaldron** [comment]
Here's an example, where instead of rethrowing and doing absolutely nothing with it, t2 will log an error instead. 

Before: 

```
$ t2 provision
Unhandled rejection Error: No key provided to set as default.
    at /Users/rwaldron/clonez/t2-cli/lib/tessel/provision.js:160:21
    at Object.actions.setDefaultKey (/Users/rwaldron/clonez/t2-cli/lib/tessel/provision.js:157:10)
    at Function.Tessel.get (/Users/rwaldron/clonez/t2-cli/lib/controller.js:121:20)
    at /Users/rwaldron/clonez/t2-cli/lib/controller.js:280:19
    at tryCatcher (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/promise.js:70:37)
    at Object.controller.standardTesselCommand (/Users/rwaldron/clonez/t2-cli/lib/controller.js:278:10)
    at executeProvision (/Users/rwaldron/clonez/t2-cli/lib/controller.js:517:25)
    at tryCatcher (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/rwaldron/clonez/t2-cli/node_modules/bluebird/js/main/async.js:15:14)
```


After: 

```
$ t2 provision
ERR! Error: No key provided to set as default.
```

**Comment by rwaldron** [comment]
(note that was done on an older branch, I just needed something to demonstrate with)

**Comment by rwaldron** [comment]
This blocks #444
