### ISSUE TITLE
Stack trace emitted in `npm install`

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#462]
It looks like the [`drivers.install()`](https://github.com/tessel/t2-cli/blob/b28c7dee90cfc86ac3f0f2f9863f9c30c574d683/bin/tessel-2.js#L65) function is not ending properly and it's causing issues with you run `npm install`.

```
/Users/Jon/Work/technical/t2-cli/bin/tessel-2.js:370
  process.exit(options.code || status.code || code);
                                     ^

TypeError: Cannot read property 'code' of undefined
    at Function.module.exports.closeFailedCommand (/Users/Jon/Work/technical/t2-cli/bin/tessel-2.js:370:38)
    at Object.cb (/Users/Jon/Work/technical/t2-cli/bin/tessel-2.js:67:22)
    at Object.ArgParser.parse (/Users/Jon/Work/technical/t2-cli/node_modules/nomnom/nomnom.js:302:15)
    at Module.module.exports (/Users/Jon/Work/technical/t2-cli/bin/tessel-2.js:347:10)
    at Object.<anonymous> (/Users/Jon/Work/technical/t2-cli/bin/tessel-2.js:375:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by johnnyman727** [comment]
Fixed by #463.
