### ISSUE TITLE
Can't create an access point over USB

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#465]
For some reason, USB throw an error when creating an access point:
```
➜  t2-cli git:(master) t2 ap -n "Frank_Net" -p "Frank_Pass"
INFO Looking for your Tessel...
INFO Connected to Tessel-02A39D970446.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Error upon remote process exit: 1
    at USBProcess.<anonymous> (/Users/Jon/Work/technical/t2-cli/lib/usb/usb_process.js:56:26)
    at USBProcess.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at USBProcess.emit (events.js:169:7)
    at Parser.<anonymous> (/Users/Jon/Work/technical/t2-cli/lib/usb/usb_daemon.js:127:14)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (/Users/Jon/Work/technical/t2-cli/node_modules/usb-daemon-parser/index.js:152:16)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Readable.push (_stream_readable.js:110:10)
```

I haven't yet dived in to see which issue is causing the problem. I usually put `console.log`s before each process creation and see where the last one was. Then I run `/etc/init.d/usbexecd restart` on the Tessel to make sure it can still respond to USB. Then I do `remoteProc.stderr.pipe(process.stderr)` for that process to make sure I get the full error message.

**Comment by rwaldron** [comment]
This is better described in https://github.com/tessel/t2-cli/issues/475

**Comment by johnnyman727** [comment]
Whoops - didn't realize I created this before. Thanks for catching that @rwaldron!
