### ISSUE TITLE
Binary Dep Failure: audiovideo

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#539]
I'm attempting to deploy [`node-audiovideo`](https://github.com/tessel/node-audiovideo) to Tessel 2. 

It won't build on OSX because one of the deps (`node-jpeg`) doesn't yet support Node 4.

I continue to install it with `npm install audiovideo --force` and used this script:
```
var av = require('audiovideo');
var fs = require('fs');

av.acquireCamera(function (err, camera) {
    camera.captureShot('jpeg').pipe(fs.createWriteStream('out.jpg'));
});

```

I get this error when I try to run it:
```
➜  av-test  t2 run index.js
INFO Looking for your Tessel...
INFO Connected to Tessel-02A34F96769C.
INFO Building project.
ERR! Error: ENOENT: no such file or directory, stat '/Users/Jon/.tessel/binaries/audiovideo-1.1.4-Release/Release/capture.node'
```

**Comment by LinusU** [comment]
If `node-jpeg` doesn't support Node 4, than it shouldn't be able to run on the Tessel either since that is using a newer node as well? Or am I missing something...

**Comment by johnnyman727** [comment]
Yes, I think that's likely but it looked like the CLI was having trouble locating the path of the actual binary (it will still fail once that's resolved).

**Comment by rwaldron** [comment]
Is there a pre-compiled binary for this module on the pre-compiled binaries server?

**Comment by rwaldron** [comment]
Not sure why, but this doesn't compile with the t2-compiler. 

```
$ ./compile.sh audiovideo@1.1.4
downloading package...
total 12
drwxrwxr-x 3 vagrant vagrant 4096 Jan 28 18:25 .
drwxr-xr-x 3 vagrant root    4096 Jan 28 18:25 ..
drwxrwxr-x 2 vagrant vagrant 4096 Jan 28 18:25 build
audiovideo-1.1.4.tgz
Connection to 127.0.0.1 closed.
running build...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7731  100  7731    0     0  47350      0 --:--:-- --:--:-- --:--:-- 47429
=> Downloading nvm as script to '/home/vagrant/.nvm'

=> Source string already in /home/vagrant/.bashrc
=> Close and reopen your terminal to start using nvm
v4.2.1 is already installed.
Now using node v4.2.1 (npm v2.14.7)
Now using node v4.2.1 (npm v2.14.7)
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color
/home/vagrant/.nvm/versions/node/v4.2.1/bin/pre-gypify -> /home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/pre-gypify/pre-gypify.js
/home/vagrant/.nvm/versions/node/v4.2.1/bin/node-pre-gyp -> /home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/node-pre-gyp/bin/node-pre-gyp
/home/vagrant/.nvm/versions/node/v4.2.1/bin/node-gyp -> /home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/node-gyp/bin/node-gyp.js
pre-gypify@1.3.2 /home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/pre-gypify
├── gyp-reader@0.0.2
└── nomnom@1.8.1 (underscore@1.6.0, chalk@0.4.0)

node-pre-gyp@0.6.19 /home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/node-pre-gyp

node-gyp@3.2.1 /home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/node-gyp
├── graceful-fs@4.1.2
├── semver@5.1.0
├── osenv@0.1.3 (os-tmpdir@1.0.1, os-homedir@1.0.1)
├── nopt@3.0.6 (abbrev@1.0.7)
├── minimatch@1.0.0 (sigmund@1.0.1, lru-cache@2.7.3)
├── fstream@1.0.8 (inherits@2.0.1)
├── which@1.2.4 (isexe@1.1.1, is-absolute@0.1.7)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@2.0.10)
├── tar@2.2.1 (inherits@2.0.1, block-stream@0.0.8)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── rimraf@2.5.1 (glob@6.0.4)
├── npmlog@1.2.1 (ansi@0.3.1, gauge@1.2.5, are-we-there-yet@1.0.6)
├── path-array@1.0.1 (array-index@1.0.0)
└── request@2.69.0 (forever-agent@0.6.1, aws-sign2@0.6.0, tunnel-agent@0.4.2, oauth-sign@0.8.0, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.1, node-uuid@1.4.7, qs@6.0.2, combined-stream@1.0.5, mime-types@2.1.9, aws4@1.2.1, form-data@1.0.0-rc3, bl@1.0.1, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@4.2.1 | linux | x64
gyp http GET https://nodejs.org/dist/v4.2.1/node-v4.2.1-headers.tar.gz
gyp http 200 https://nodejs.org/dist/v4.2.1/node-v4.2.1-headers.tar.gz
gyp http GET https://nodejs.org/dist/v4.2.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/dist/v4.2.1/SHASUMS256.txt
4.2.1
gyp info ok
+ pre-gypify --package_name '{name}-{version}-{configuration}.tgz'
writing package.json...
kk
+ export STAGING_DIR=/home/vagrant/
+ STAGING_DIR=/home/vagrant/
+ export NODEGYP=node-gyp
+ NODEGYP=node-gyp
+ export NODE=4.2.1
+ NODE=4.2.1
+ export TOOLCHAIN_ARCH=mipsel
+ TOOLCHAIN_ARCH=mipsel
+ echo OHOHOH
OHOHOH
+ echo mipsel
mipsel
+ echo 4.2.1
4.2.1
+ set -e
+ '[' '!' -d /home/vagrant/ ']'
+ ARCH=mipsel
+ NODE=4.2.1
+ NODEGYP=node-gyp
++ ls -d /home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2
+ TOOLCHAIN_DIR=/home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2
+ echo /home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2
/home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2
++ ls -d /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2
+ export SYSROOT=/home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2
+ SYSROOT=/home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2
+ source /home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/info.mk
++ TARGET_CROSS=mipsel-openwrt-linux-uclibc-
++ GCC_VERSION=4.8-linaro
++ LIBC_TYPE=uClibc
++ LIBC_URL=http://www.uclibc.org/
++ LIBC_VERSION=0.9.33.2
++ LIBC_SO_VERSION=0.9.33.2
+ echo 'Cross-compiling for' mipsel-openwrt-linux-uclibc-
Cross-compiling for mipsel-openwrt-linux-uclibc-
+ export PATH=/home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin:/home/vagrant/.nvm/versions/node/v4.2.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
+ PATH=/home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin:/home/vagrant/.nvm/versions/node/v4.2.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
+ export CPPPATH=/usr/include
+ CPPPATH=/usr/include
+ export LIBPATH=/usr/lib
+ LIBPATH=/usr/lib
+ OPTS='-I /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -L /home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib -L /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib'
+ export 'CC=mipsel-openwrt-linux-uclibc-gcc -I /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -L /home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib -L /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib'
+ CC='mipsel-openwrt-linux-uclibc-gcc -I /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -L /home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib -L /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib'
+ export 'CXX=mipsel-openwrt-linux-uclibc-g++ -I /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -L /home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib -L /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib'
+ CXX='mipsel-openwrt-linux-uclibc-g++ -I /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -L /home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib -L /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib'
+ export AR=mipsel-openwrt-linux-uclibc-ar
+ AR=mipsel-openwrt-linux-uclibc-ar
+ export RANLIB=mipsel-openwrt-linux-uclibc-ranlib
+ RANLIB=mipsel-openwrt-linux-uclibc-ranlib
+ export 'LINK=mipsel-openwrt-linux-uclibc-g++ -I /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -L /home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib -L /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib'
+ LINK='mipsel-openwrt-linux-uclibc-g++ -I /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -L /home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib -L /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib'
+ export 'CPP=mipsel-openwrt-linux-uclibc-gcc -I /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -L /home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib -L /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib -E'
+ CPP='mipsel-openwrt-linux-uclibc-gcc -I /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -L /home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib -L /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib -E'
+ export STRIP=mipsel-openwrt-linux-uclibc-strip
+ STRIP=mipsel-openwrt-linux-uclibc-strip
+ export OBJCOPY=mipsel-openwrt-linux-uclibc-objcopy
+ OBJCOPY=mipsel-openwrt-linux-uclibc-objcopy
+ export 'LD=mipsel-openwrt-linux-uclibc-g++ -I /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -L /home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib -L /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib'
+ LD='mipsel-openwrt-linux-uclibc-g++ -I /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -L /home/vagrant//toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib -L /home/vagrant//target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib'
+ export OBJDUMP=mipsel-openwrt-linux-uclibc-objdump
+ OBJDUMP=mipsel-openwrt-linux-uclibc-objdump
+ export NM=mipsel-openwrt-linux-uclibc-nm
+ NM=mipsel-openwrt-linux-uclibc-nm
+ export AS=mipsel-openwrt-linux-uclibc-as
+ AS=mipsel-openwrt-linux-uclibc-as
+ export npm_config_arch=mipsel
+ npm_config_arch=mipsel
++ which node-gyp
+ export npm_config_node_gyp=/home/vagrant/.nvm/versions/node/v4.2.1/bin/node-gyp
+ npm_config_node_gyp=/home/vagrant/.nvm/versions/node/v4.2.1/bin/node-gyp
+ npm install --ignore-scripts
npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror https://github.com/tcr/node-jpeg.git /home/vagrant/.npm/_git-remotes/https-github-com-tcr-node-jpeg-git-082a82ed: undefined
npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror https://github.com/tcr/node-jpeg.git /home/vagrant/.npm/_git-remotes/https-github-com-tcr-node-jpeg-git-082a82ed: undefined
npm ERR! Linux 3.13.0-65-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.2.1/bin/node" "/home/vagrant/.nvm/versions/node/v4.2.1/bin/npm" "install" "--ignore-scripts"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /work/binary-module/package/npm-debug.log
Connection to 127.0.0.1 closed.
```

cc @tcr

**Comment by johnnyman727** [comment]
I believe @tcr has a branch that fixes these errors and that generated the build that's currently on packages.tessel.io.

**Comment by rwaldron** [comment]
Well, if @tcr wants to push that branch so I can generate it locally and walk through the build process, that would be great.

**Comment by rwaldron** [comment]
I will try to see what I can learn from the existing pre-compiled binary

**Comment by rwaldron** [comment]
When I look at the installed and (force) built `audiovideo` module's directory, it looks like `capture.node` was created in two places? Once where it was expected and one that's not in a commonly used path: 

Here's how I discovered this: 

```
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to ash.
mPath:  node_modules/audiovideo/build/Release/capture.node
mPath:  node_modules/audiovideo/src/binding/capture.node
INFO Building project.
```

Here's a slightly elided directory view: 

```
$ tree -L 3
.
├── README.md
├── binding.gyp
├── build
│   ├── Makefile
│   ├── Release
│   │   ├── capture.node
│   │   ├── linker.lock
│   │   └── obj.target
│   ├── action_after_build.target.mk
│   ├── binding.Makefile
│   ├── capture.target.mk
│   ├── config.gypi
│   └── gyp-mac-tool
├── index.js
├── package.json
├── src
│   ├── binding
│   │   └── capture.node
│   ├── capture.m
│   └── capture_module.cc
...
```

Notice `capture.node` is found twice—I don't think it's necessary for `audiovideo` to over complicate its gyp rules like this\*. It could be argued that t2-cli should be able to figure out _any_ path to a `compiled.node`, which I readily agree, however it's actually not possible for any code to disambiguate this: 

```
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to ash.
mPath:  node_modules/audiovideo/build/Release/capture.node
mPath:  node_modules/audiovideo/src/binding/capture.node
INFO Building project.
```

Nothing about that infers anything that we can use to determine which is the right one to track, ie. which path the downloaded tar.gz will extract to. Note that `audiovideo` is compiling to a directory that is actually outside of known paths used by the well known `bindings` module: https://github.com/TooTallNate/node-bindings/blob/master/bindings.js#L18-L34, so using that to solve the directory location is impossible. To further complicate matters, the tar.gz on packages.tessel.io unzips to this: 

```
rwaldron at new-host-4 in ~/.tessel/binaries/audiovideo-1.1.4-Release
$ tree
.
└── binding
    └── capture.node
```

Even if we used the `src/binding/capture.node` found above, the injection operation would never find this `capture.node`, because it just doesn't know where to look. At this point, it's like `audiovideo` is trolling the deployment operation.

**Comment by rwaldron** [comment]
Also, the `jpeg` module needs to be precompiled as well.

**Comment by tcr** [comment]
The `jpeg` module is very out of date and we may want to publish a new one, i.e. `nan-jpeg`, or perhaps ping @pkrumins about considering https://github.com/pkrumins/node-jpeg/pull/22.

I had no issues compiling node-jpeg on t2-compiler, but it being a branch is probably contributing to its issue.

**Comment by tcr** [comment]
Temporary fork: https://github.com/tessel/node-libjpeg

**Comment by johnnyman727** [comment]
"temporary"

**Comment by rwaldron** [comment]
> I had no issues compiling node-jpeg on t2-compiler, but it being a branch is probably contributing to its issue.

Which "version" of node-jpeg? I tried: 

```
./compile.sh git+https://github.com/tcr/node-jpeg.git#tcr-nan2
``` 

Which had this result: 

```
  CXX(target) Debug/obj.target/jpeg/src/common.o
  CXX(target) Debug/obj.target/jpeg/src/jpeg_encoder.o
In file included from ../src/jpeg_encoder.cpp:1:0:
../src/jpeg_encoder.h:6:21: fatal error: jpeglib.h: No such file or directory
 #include <jpeglib.h>
                     ^
compilation terminated.
```

(I've elided most of the output)

I've also just now tried this: 

```
./compile.sh libjpeg
```

Which has the same result as above.

**Comment by johnnyman727** [comment]
@rwaldron did you flash your Tessel with a latest build from https://github.com/tessel/openwrt-tessel?

**Comment by johnnyman727** [comment]
Or rather, I think the issue is just that the cross compiled toolchain hasn't been updated here:
https://github.com/tessel/t2-compiler/blob/master/Vagrantfile#L71

**Comment by johnnyman727** [comment]
I'm still not able to get this to compile. @tcr maybe you can help.

I checked out tessel/openwrt-tessel at master (where you have added the libjpeg dep) and built it. I then placed the toolchain binaries into a folder and uploaded the tarball exactly where the `t2-compiler` is looking:

https://github.com/tessel/t2-compiler/blob/master/Vagrantfile#L71

I then deleted by old vagrant instance (`vagrant destroy`) and created a new one (`vagrant reload`).

Then I tried compiling again by running `./compile.sh git+ssh://git@github.com:tessel/node-libjpeg.git` (so it's pointing at our temporary fork. 

It still fails with the "missing jpeglib.h" error that @rwaldron reported.

**Comment by johnnyman727** [comment]
Next steps are to clean up `audiovideo` to only output one binary and make a new npm publish/binary module server publish for `audiovideo@1.2.0`.

**Comment by johnnyman727** [comment]
I've published `audiovideo@1.2.0` to packages.tessel.io. It fails to compile on OSX but I'm not sure if that's an issue. I just forced the install to make sure all the relevant directories exist (`npm install https://github.com/tessel/node-audiovideo --force`).

I tried a simple `t2 run index.js` again but the only binding the CLI found was for `audiovideo` itself so when it was run on the device, I got the following issue:
```.bash
➜  av-test  t2 run index.js
INFO Looking for your Tessel...
INFO Connected to Horse.
INFO Building project.
INFO Writing project to RAM on Horse (87.04 kB)...
INFO Deployed.
INFO Running index.js...
module.js:339
    throw err;
    ^

Error: Cannot find module 'libjpeg'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/remote-script/node_modules/audiovideo/index.js:1:348)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

I figured this is probably do to the binary dep not being pulled from the builds server so I tried to manually copy over the `libjpeg` binary into the `/node_modules/libjpeg/build/Release` folder. I still couldn't get the code to run:
```
module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^
 
Error: File not found
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/remote-script/node_modules/audiovideo/index.js:1:348)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

Running out of ideas for the night.

**Comment by rwaldron** [comment]
I've spent significant amount of time with this issue over the last two days and I've determined that this is absolutely not an issue in t2-cli

**Comment by johnnyman727** [comment]
@rwaldron do you know why CLI doesn't try to inject the libjpeg binary dep?

**Comment by rwaldron** [comment]
> do you know why CLI doesn't try to inject the libjpeg binary dep?


I suspect it's because it doesn't get built...

```
$ npm install https://github.com/tessel/node-audiovideo --force
npm WARN using --force I sure hope you know what you are doing.
|
> libjpeg@3.0.0 install /Users/rwaldron/robotz/tessel-libjpeg/node_modules/audiovideo/node_modules/libjpeg
> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/jpeg/src/common.o
  CXX(target) Release/obj.target/jpeg/src/jpeg_encoder.o
In file included from ../src/jpeg_encoder.cpp:1:
../src/jpeg_encoder.h:6:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
         ^
1 error generated.
make: *** [Release/obj.target/jpeg/src/jpeg_encoder.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/rwaldron/robotz/tessel-libjpeg/node_modules/audiovideo/node_modules/libjpeg/bindings/jpeg.node" "--module_name=jpeg" "--module_path=/Users/rwaldron/robotz/tessel-libjpeg/node_modules/audiovideo/node_modules/libjpeg/bindings"
gyp ERR! cwd /Users/rwaldron/robotz/tessel-libjpeg/node_modules/audiovideo/node_modules/libjpeg
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/rwaldron/robotz/tessel-libjpeg/node_modules/audiovideo/node_modules/libjpeg/bindings/jpeg.node --module_name=jpeg --module_path=/Users/rwaldron/robotz/tessel-libjpeg/node_modules/audiovideo/node_modules/libjpeg/bindings' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/rwaldron/robotz/tessel-libjpeg/node_modules/audiovideo/node_modules/libjpeg/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.3.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/rwaldron/robotz/tessel-libjpeg/node_modules/audiovideo/node_modules/libjpeg/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/rwaldron/robotz/tessel-libjpeg/node_modules/audiovideo/node_modules/libjpeg
node-pre-gyp ERR! node -v v4.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.18
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/rwaldron/robotz/tessel-libjpeg/node_modules/audiovideo/node_modules/libjpeg/bindings/jpeg.node --module_name=jpeg --module_path=/Users/rwaldron/robotz/tessel-libjpeg/node_modules/audiovideo/node_modules/libjpeg/bindings' (1)
```

![](https://i.gyazo.com/5df3c7cbebf335f15cadcd2c32d6e160.png)



TBH, it's felt very wasteful to approach this from a "bug in t2-cli" perspective.

**Comment by rwaldron** [comment]
Also: 

> Edit: compiling libjpeg is working now. You'll have to vagrant destroy; vagrant provision to get the new cross compiler tar ball.

Has left me with an unusable t2-compiler vm.

**Comment by rwaldron** [comment]
> I suspect it's because it doesn't get built...


> TBH, it's felt very wasteful to approach this from a "bug in t2-cli" perspective.

More thoughts on this...

I'm going to work on making binary deps detectable even when the `.node` binary isn't present, but this is absolutely not the issue to track the work in.

**Comment by rwaldron** [comment]
https://github.com/tessel/t2-cli/issues/542
