### ISSUE TITLE
For the love of god help Travis find Wrappy

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#573]
Our Travis CI build have false negatives very often because Travis claims that it can't find the module `wrappy`. The fix is to just rerun the test. This happens to virtually every PR and it's maddening. Log output is below:
```
Worker information
hostname: travis-worker-gce-org-prod-10:25833b00-9cd8-4785-b5aa-feb8c47f8d79
version: v2.1.0-44-ge7ef5db https://github.com/travis-ci/worker/tree/e7ef5db4f469f8e76792dee8309e601b6e53e56b
instance: testing-gce-0e80cede-350b-4907-99c7-1436b80746b5:travis-ci-nodejs-precise-1450195912
startup: 21.296632401s
Build system information
Build language: node_js
Build group: stable
Build dist: precise
Build image provisioning date and time
Tue Dec 15 16:30:53 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-63-generic
Cookbooks Version
fad6c97 https://github.com/travis-ci/travis-cookbooks/tree/fad6c97
Git version
git version 1.8.5.6
bash version
GNU bash, version 4.2.25(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
iojs-v1.1.0
v0.10
v0.10.18
v0.10.36
v0.11.15
v0.6.21
v0.8.27
Pre-installed Go versions
1.4.2
mysql --version
mysql  Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (x86_64) using readline 6.2
Pre-installed PostgreSQL versions
9.1.19
9.2.14
9.3.10
9.4.5
Redis version
redis-server 3.0.5
riak version
2.1.3
MongoDB version
MongoDB 2.4.14
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
Cassandra version
2.0.9
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 38.4.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-63-generic", arch: "amd64", family: "unix"

$ git clone --depth=50 https://github.com/tessel/t2-cli.git tessel/t2-cli
Cloning into 'tessel/t2-cli'...
remote: Counting objects: 1888, done.
remote: Compressing objects: 100% (725/725), done.
remote: Total 1888 (delta 1261), reused 1704 (delta 1100), pack-reused 0
Receiving objects: 100% (1888/1888), 466.12 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1261/1261), done.
Checking connectivity... done.

$ cd tessel/t2-cli
$ git fetch origin +refs/pull/571/merge:
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 15 (delta 11), reused 15 (delta 11), pack-reused 0
Unpacking objects: 100% (15/15), done.
From https://github.com/tessel/t2-cli
 * branch            refs/pull/571/merge -> FETCH_HEAD

$ git checkout -qf FETCH_HEAD
Adding APT Sources (BETA)
$ export DEBIAN_FRONTEND=noninteractive
$ sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
gpg: keyring `/tmp/tmp3wfwke/secring.gpg' created
gpg: keyring `/tmp/tmp3wfwke/pubring.gpg' created
gpg: requesting key BA9EF27F from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp3wfwke/trustdb.gpg: trustdb created
gpg: key BA9EF27F: public key "Launchpad Toolchain builds" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK

Installing APT Packages (BETA)
$ export DEBIAN_FRONTEND=noninteractive
$ sudo -E apt-get -yq update &>> ~/apt-get-update.log

$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install g++-4.8
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  cpp-4.8 gcc-4.8 gcc-4.8-base gcc-5-base libasan0 libatomic1 libcloog-isl4
  libgcc-4.8-dev libgcc1 libgomp1 libisl10 libitm1 libquadmath0
  libstdc++-4.8-dev libstdc++6 libtsan0
Suggested packages:
  gcc-4.8-locales g++-4.8-multilib gcc-4.8-doc libstdc++6-4.8-dbg
  gcc-4.8-multilib libmudflap0-4.8-dev libgcc1-dbg libgomp1-dbg libitm1-dbg
  libatomic1-dbg libasan0-dbg libtsan0-dbg libbacktrace1-dbg libquadmath0-dbg
  libmudflap0-dbg binutils-gold libstdc++-4.8-doc
The following NEW packages will be installed:
  cpp-4.8 g++-4.8 gcc-4.8 gcc-4.8-base gcc-5-base libasan0 libatomic1
  libcloog-isl4 libgcc-4.8-dev libisl10 libitm1 libstdc++-4.8-dev libtsan0
The following packages will be upgraded:
  libgcc1 libgomp1 libquadmath0 libstdc++6
4 upgraded, 13 newly installed, 0 to remove and 116 not upgraded.
Need to get 27.4 MB of archives.
After this operation, 69.1 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main gcc-5-base amd64 5.2.1-23ubuntu1~12.04 [17.9 kB]
Get:2 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main libgcc1 amd64 1:5.2.1-23ubuntu1~12.04 [44.9 kB]
Get:3 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main libstdc++6 amd64 5.2.1-23ubuntu1~12.04 [382 kB]
Get:4 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main gcc-4.8-base amd64 4.8.1-2ubuntu1~12.04 [16.0 kB]
Get:5 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main libasan0 amd64 4.8.1-2ubuntu1~12.04 [76.0 kB]
Get:6 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main libatomic1 amd64 5.2.1-23ubuntu1~12.04 [10.5 kB]
Get:7 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main libisl10 amd64 0.12.2-2~12.04 [530 kB]
Get:8 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main libcloog-isl4 amd64 0.18.2-1~12.04 [67.3 kB]
Get:9 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main libgomp1 amd64 5.2.1-23ubuntu1~12.04 [63.7 kB]
Get:10 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main libitm1 amd64 5.2.1-23ubuntu1~12.04 [33.6 kB]
Get:11 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main libquadmath0 amd64 5.2.1-23ubuntu1~12.04 [145 kB]
Get:12 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main libtsan0 amd64 5.2.1-23ubuntu1~12.04 [309 kB]
Get:13 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main cpp-4.8 amd64 4.8.1-2ubuntu1~12.04 [5,835 kB]
Get:14 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main libgcc-4.8-dev amd64 4.8.1-2ubuntu1~12.04 [2,792 kB]
Get:15 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main gcc-4.8 amd64 4.8.1-2ubuntu1~12.04 [6,609 kB]
Get:16 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main libstdc++-4.8-dev amd64 4.8.1-2ubuntu1~12.04 [1,753 kB]
Get:17 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/ precise/main g++-4.8 amd64 4.8.1-2ubuntu1~12.04 [8,707 kB]
Fetched 27.4 MB in 7s (3,449 kB/s)
Selecting previously unselected package gcc-5-base.
(Reading database ... 124622 files and directories currently installed.)
Unpacking gcc-5-base (from .../gcc-5-base_5.2.1-23ubuntu1~12.04_amd64.deb) ...
Processing triggers for ccache ...
Updating symlinks in /usr/lib/ccache ...
Setting up gcc-5-base (5.2.1-23ubuntu1~12.04) ...
(Reading database ... 124629 files and directories currently installed.)
Preparing to replace libgcc1 1:4.6.3-1ubuntu5 (using .../libgcc1_1%3a5.2.1-23ubuntu1~12.04_amd64.deb) ...
Unpacking replacement libgcc1 ...
Setting up libgcc1 (1:5.2.1-23ubuntu1~12.04) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
(Reading database ... 124629 files and directories currently installed.)
Preparing to replace libstdc++6 4.6.3-1ubuntu5 (using .../libstdc++6_5.2.1-23ubuntu1~12.04_amd64.deb) ...
Unpacking replacement libstdc++6 ...
Setting up libstdc++6 (5.2.1-23ubuntu1~12.04) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
Selecting previously unselected package gcc-4.8-base.
(Reading database ... 124642 files and directories currently installed.)
Unpacking gcc-4.8-base (from .../gcc-4.8-base_4.8.1-2ubuntu1~12.04_amd64.deb) ...
Selecting previously unselected package libasan0.
Unpacking libasan0 (from .../libasan0_4.8.1-2ubuntu1~12.04_amd64.deb) ...
Selecting previously unselected package libatomic1.
Unpacking libatomic1 (from .../libatomic1_5.2.1-23ubuntu1~12.04_amd64.deb) ...
Selecting previously unselected package libisl10.
Unpacking libisl10 (from .../libisl10_0.12.2-2~12.04_amd64.deb) ...
Selecting previously unselected package libcloog-isl4.
Unpacking libcloog-isl4 (from .../libcloog-isl4_0.18.2-1~12.04_amd64.deb) ...
Preparing to replace libgomp1 4.6.3-1ubuntu5 (using .../libgomp1_5.2.1-23ubuntu1~12.04_amd64.deb) ...
Unpacking replacement libgomp1 ...
Selecting previously unselected package libitm1.
Unpacking libitm1 (from .../libitm1_5.2.1-23ubuntu1~12.04_amd64.deb) ...
Preparing to replace libquadmath0 4.6.3-1ubuntu5 (using .../libquadmath0_5.2.1-23ubuntu1~12.04_amd64.deb) ...
Unpacking replacement libquadmath0 ...
Selecting previously unselected package libtsan0.
Unpacking libtsan0 (from .../libtsan0_5.2.1-23ubuntu1~12.04_amd64.deb) ...
Selecting previously unselected package cpp-4.8.
Unpacking cpp-4.8 (from .../cpp-4.8_4.8.1-2ubuntu1~12.04_amd64.deb) ...
Selecting previously unselected package libgcc-4.8-dev.
Unpacking libgcc-4.8-dev (from .../libgcc-4.8-dev_4.8.1-2ubuntu1~12.04_amd64.deb) ...
Selecting previously unselected package gcc-4.8.
Unpacking gcc-4.8 (from .../gcc-4.8_4.8.1-2ubuntu1~12.04_amd64.deb) ...
Selecting previously unselected package libstdc++-4.8-dev.
Unpacking libstdc++-4.8-dev (from .../libstdc++-4.8-dev_4.8.1-2ubuntu1~12.04_amd64.deb) ...
Selecting previously unselected package g++-4.8.
Unpacking g++-4.8 (from .../g++-4.8_4.8.1-2ubuntu1~12.04_amd64.deb) ...
Processing triggers for ccache ...
Updating symlinks in /usr/lib/ccache ...
Processing triggers for man-db ...
Setting up gcc-4.8-base (4.8.1-2ubuntu1~12.04) ...
Setting up libasan0 (4.8.1-2ubuntu1~12.04) ...
Setting up libatomic1 (5.2.1-23ubuntu1~12.04) ...
Setting up libisl10 (0.12.2-2~12.04) ...
Setting up libcloog-isl4 (0.18.2-1~12.04) ...
Setting up libgomp1 (5.2.1-23ubuntu1~12.04) ...
Setting up libitm1 (5.2.1-23ubuntu1~12.04) ...
Setting up libquadmath0 (5.2.1-23ubuntu1~12.04) ...
Setting up libtsan0 (5.2.1-23ubuntu1~12.04) ...
Setting up cpp-4.8 (4.8.1-2ubuntu1~12.04) ...
Setting up libgcc-4.8-dev (4.8.1-2ubuntu1~12.04) ...
Setting up gcc-4.8 (4.8.1-2ubuntu1~12.04) ...
Setting up libstdc++-4.8-dev (4.8.1-2ubuntu1~12.04) ...
Setting up g++-4.8 (4.8.1-2ubuntu1~12.04) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place


Setting environment variables from repository settings
$ export MOCK_USB=[secure]

Setting environment variables from .travis.yml
$ export CXX=g++-4.8

$ nvm install 4.2.1
######################################################################## 100.0%
Checksums empty
Now using node v4.2.1

$ node --version
v4.2.1
$ npm --version
2.14.7
$ nvm --version
0.23.3
$ npm install -g grunt-cli
/home/travis/.nvm/versions/node/v4.2.1/bin/grunt -> /home/travis/.nvm/versions/node/v4.2.1/lib/node_modules/grunt-cli/bin/grunt
grunt-cli@0.1.13 /home/travis/.nvm/versions/node/v4.2.1/lib/node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.7)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)

$ sudo apt-get update -qq

$ sudo apt-get install pkg-config build-essential libusb-1.0-0-dev libudev-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pkg-config is already the newest version.
pkg-config set to manually installed.
build-essential is already the newest version.
The following extra packages will be installed:
  libudev0
The following NEW packages will be installed:
  libudev-dev libusb-1.0-0-dev
The following packages will be upgraded:
  libudev0
1 upgraded, 2 newly installed, 0 to remove and 115 not upgraded.
Need to get 249 kB of archives.
After this operation, 1,445 kB of additional disk space will be used.
Get:1 http://us-central1.gce.archive.ubuntu.com/ubuntu/ precise-updates/main libudev0 amd64 175-0ubuntu9.10 [27.8 kB]
Get:2 http://us-central1.gce.archive.ubuntu.com/ubuntu/ precise-updates/main libudev-dev amd64 175-0ubuntu9.10 [62.6 kB]
Get:3 http://us-central1.gce.archive.ubuntu.com/ubuntu/ precise/main libusb-1.0-0-dev amd64 2:1.0.9~rc3-2ubuntu1 [158 kB]
Fetched 249 kB in 0s (11.3 MB/s)
(Reading database ... 125563 files and directories currently installed.)
Preparing to replace libudev0 175-0ubuntu9.9 (using .../libudev0_175-0ubuntu9.10_amd64.deb) ...
Unpacking replacement libudev0 ...
Selecting previously unselected package libudev-dev.
Unpacking libudev-dev (from .../libudev-dev_175-0ubuntu9.10_amd64.deb) ...
Selecting previously unselected package libusb-1.0-0-dev.
Unpacking libusb-1.0-0-dev (from .../libusb-1.0-0-dev_2%3a1.0.9~rc3-2ubuntu1_amd64.deb) ...
Setting up libudev0 (175-0ubuntu9.10) ...
Setting up libudev-dev (175-0ubuntu9.10) ...
Setting up libusb-1.0-0-dev (2:1.0.9~rc3-2ubuntu1) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place

$ npm install
npm WARN engine mdns-js@0.4.0: wanted: {"node":"^0.10.3 || ^0.12.0"} (current: {"node":"4.2.1","npm":"2.14.7"})
npm WARN deprecated lodash@0.9.2: Grunt needs your help! See https://github.com/gruntjs/grunt/issues/1403.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

> usb@1.1.1 install /home/travis/build/tessel/t2-cli/node_modules/usb
> node-pre-gyp install --fallback-to-build

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: Cannot find module 'wrappy'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:337:15)
gyp ERR! stack     at Function.Module._load (module.js:287:25)
gyp ERR! stack     at Module.require (module.js:366:17)
gyp ERR! stack     at require (module.js:385:17)
gyp ERR! stack     at Object.<anonymous> (/home/travis/build/tessel/t2-cli/node_modules/npm/node_modules/inflight/inflight.js:1:76)
gyp ERR! stack     at Module._compile (module.js:435:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:442:10)
gyp ERR! stack     at Module.load (module.js:356:32)
gyp ERR! stack     at Function.Module._load (module.js:311:12)
gyp ERR! stack     at Module.require (module.js:366:17)
gyp ERR! System Linux 3.13.0-63-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v4.2.1/bin/node" "/home/travis/build/tessel/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /home/travis/build/tessel/t2-cli/node_modules/usb
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/travis/.nvm/versions/node/v4.2.1/bin/node /home/travis/build/tessel/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/travis/build/tessel/t2-cli/node_modules/usb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.13.0-63-generic
node-pre-gyp ERR! command "/home/travis/.nvm/versions/node/v4.2.1/bin/node" "/home/travis/build/tessel/t2-cli/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/travis/build/tessel/t2-cli/node_modules/usb
node-pre-gyp ERR! node -v v4.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/home/travis/.nvm/versions/node/v4.2.1/bin/node /home/travis/build/tessel/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (7)
npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.2.1/bin/node" "/home/travis/.nvm/versions/node/v4.2.1/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! usb@1.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the usb@1.1.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the usb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls usb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/tessel/t2-cli/npm-debug.log


The command "npm install" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by LinusU** [comment]
I've encountered this with another dependency than wrappy as well...

Also, the strange thing is that I restarted it 4 times before giving up, but then letting it sit for a while, it seemed like it worked on the first restart...

**Comment by johnnyman727** [comment]
@LinusU do you think this is an issue with `NPM`, Travis, our CLI, or the specific module?

**Comment by LinusU** [comment]
I'm leaning against npm actually, but I'm not 100% sure. I've seen a lot of problems with npm after they released version 3 so I wouldn't be surprised...

Looking thru the npm issues now but they seem to be getting in a ton of bugs a day so it's very hard to find relevant info...

**Comment by LinusU** [comment]
Hmm, it always seems to be in the `npm` dependency though, I wonder if that's significant....

**Comment by johnnyman727** [comment]
So it always fails finding one of `npm`'s dependencies but it also fails with a `usb` error:
```
Failed at the usb@1.1.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the usb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls usb
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/tessel/t2-cli/npm-debug.log
```

I'm not sure if one is causing the other. Also, #585 is not able to pass at all even after about a dozen restarts...

**Comment by asez73** [comment]
Hello,
I can confirm this also when installing on ubuntu 14.04 with updated nodejs 4.4.2 and npm 2.15.0.
I more or less solved it by "sudo npm install usb -g" but failed on 
> t2-cli@0.0.16 postinstall /home/alain/.npm-global/lib/node_modules/t2-cli
> t2 install-drivers || true

*** Error in `node': free(): invalid pointer: 0x000000000326e1ef ***
Aborted (core dumped)
