### ISSUE TITLE
Wifi connect finishes with error

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#575]
When I ran `t2 wifi -n SSID -p PASS` on a freshly flashed Tessel (0.0.11), the connection attempt succeeded but the following error was thrown:
```
INFO Wifi connection successful. SSID: REDACTED, password REDACTED, security mode: REDACTED
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Connection was already closed...
    at USB.Connection.exec.USB.Connection._write (/Users/Jon/Work/technical/t2-cli/lib/usb_connection.js:89:14)
    at doWrite (_stream_writable.js:292:12)
    at clearBuffer (_stream_writable.js:396:7)
    at onwrite (_stream_writable.js:331:7)
    at OutEndpoint.WritableState.onwrite (_stream_writable.js:89:5)
    at Transfer.callback (/Users/Jon/Work/technical/t2-cli/node_modules/usb/usb.js:362:14)
```

Steps to reproduce:
* [Download the `0.0.11` binary](https://github.com/tessel/openwrt-tessel/releases/download/0.0.11/openwrt.bin)
* scp it to the `/tmp` folder of your Tessel
* run `sysupgrade -n` with the path that image
* on your machine, attempt to connect to wifi with `t2 wifi -n SSID -p PASS`

**Comment by HipsterBrown** [comment]
Will look into this today as well.

**Comment by HipsterBrown** [comment]
Have not been able to re-create this issue. Is it still happening?

**Comment by johnnyman727** [comment]
I haven't been able to repro it either. I'm fine closing this for now.
