### ISSUE TITLE
FRE Tweet example doesn't work

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#587]
When I walk through the [First Run Experience's Tweet example](http://tessel.github.io/t2-start/tweet.html), my Tessel fails to deploy the code. It gets stuck with:
```
➜  tessel-tweet t2 run tweet.js
INFO Looking for your Tessel...
INFO Connected to Hose.
INFO Building project.
```
It does not hang if I run it with the `--full` flag.

Workaround is `t2 run tweet.js --full`.

**Comment by johnnyman727** [comment]
The error is being thrown [here](https://github.com/tessel/t2-cli/blob/e016516aed2ea76ed50605a79d4b75fd61ffc68f/lib/tessel/deploy.js#L797) but it's being swallowed for some reason. 

When I print out the stack trace for the error, it looks like:
```
TypeError: self.key.print is not a function
    at eval (eval at <anonymous> (/Users/Jon/Work/technical/t2-cli/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:4826:18)
    at doit (eval at <anonymous> (/Users/Jon/Work/technical/t2-cli/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:4067:13)
    at AST_Node.eval [as print] (eval at <anonymous> (/Users/Jon/Work/technical/t2-cli/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:4073:13)
    at eval (eval at <anonymous> (/Users/Jon/Work/technical/t2-cli/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:4793:22)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/Users/Jon/Work/technical/t2-cli/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:4787:29)
    at eval (eval at <anonymous> (/Users/Jon/Work/technical/t2-cli/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:3946:19)
    at OutputStream.with_indent (eval at <anonymous> (/Users/Jon/Work/technical/t2-cli/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:3920:38)
    at Object.with_block (eval at <anonymous> (/Users/Jon/Work/technical/t2-cli/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:3945:9)
    at eval (eval at <anonymous> (/Users/Jon/Work/technical/t2-cli/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:4786:48)
```

So my guess is that `uglify` has some bug inside it. @rwaldron what do you think?

**Comment by rwaldron** [comment]
I have an idea... What if we just forward JS source "as-is" if the compression fails? That would also address our woes w/r to lack of ES6 support in minified. I'll get a patch written asap
