### ISSUE TITLE
single file option for `run` doesn't work anymore

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#624]
I tried deploying just a single file (with the `-s` flag) and the CLI sent the entire bundle.

**Comment by rwaldron** [comment]
I'm afraid our existing tests might not have been sufficient for this path :angry: 

I'll get this resolved asap.

**Comment by rwaldron** [comment]
When I tested this just now, only the single file was sent. 

```
mkdir tessel-init; cd tessel-init; 
t2 init;
npm install math-euler;
echo "var Euler = require('math-euler');" > index.js;
t2 run index.js -s;
```

Result: 

```
INFO Looking for your Tessel...
INFO Connected to bishop.
INFO Building project.
INFO Writing project to RAM on bishop (2.048 kB)...
INFO Deployed.
INFO Running index.js...
module.js:339
    throw err;
    ^

Error: Cannot find module 'math-euler'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/remote-script/index.js:1:69)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```


Confirmed by ssh to board: 

```
$ ssh root@bishop.local -i ~/.tessel/id_rsa

BusyBox v1.23.2 (2015-12-16 06:42:04 UTC) built-in shell (ash)

Tessel 2  /  Built on OpenWrt
root@bishop:~# cd /tmp/remote-script/ && ls
index.js
```

**Comment by rwaldron** [comment]
I _did_ discover that -s isn't ignoring `.tesselinclude` matches.

**Comment by rwaldron** [comment]
Also, binary modules are incorrectly included as well. Fix coming.
