### ISSUE TITLE
t2 update fails with javascript error

### ISSUE THREAD

**Issue by josser** [tessel/t2-cli#641]
Here is log: 

```
t2 update
INFO Looking for your Tessel...
INFO Connected to josser-tessel.
INFO New firmware version found...0.0.12
INFO Updating josser-tessel to latest version (0.0.12)...
INFO Beginning update download. This could take a couple minutes..
/Users/josser/.nvm/versions/node/v4.4.2/lib/node_modules/t2-cli/node_modules/progress/lib/node-progress.js:131
  complete = Array(completeLength + 1).join(this.chars.complete);
             ^

RangeError: Invalid array length
    at ProgressBar.render (/Users/josser/.nvm/versions/node/v4.4.2/lib/node_modules/t2-cli/node_modules/progress/lib/node-progress.js:131:14)
    at ProgressBar.tick (/Users/josser/.nvm/versions/node/v4.4.2/lib/node_modules/t2-cli/node_modules/progress/lib/node-progress.js:86:8)
    at IncomingMessage.<anonymous> (/Users/josser/.nvm/versions/node/v4.4.2/lib/node_modules/t2-cli/lib/update-fetch.js:126:13)
    at emitOne (events.js:82:20)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.Readable.read (_stream_readable.js:368:10)
    at flow (_stream_readable.js:751:26)
    at resume_ (_stream_readable.js:731:3)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

Tried both on 4 and 5 node.

**Comment by johnnyman727** [comment]
looking into it now...

**Comment by johnnyman727** [comment]
I think I've fixed it but testing now...

**Comment by johnnyman727** [comment]
Okay @josser can you give it another try?

**Comment by josser** [comment]
Ok, I've found the reason

it trying to download file from 
https://builds.tessel.io/t2/firmware/f295bc69dc0aae06fdc14ee4027d2889c30fbbac.tar.gz

But file is missing or access is denied so cloud-front return this: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>62067A7AABF1DD9D</RequestId><HostId>i52nVticmXsq1BUUTnvqttFQ0F6LdGgDPrVpjooHovcVcxEH4ZOX8Bm9z3Ha/3y5t3v9uhN1KpI=</HostId></Error>%                                                            
```

and there is no content-length in response headers.
And so, it fails to calculate total length of progress bar because it calculated in that way:

```javascript
 var len = parseInt(res.headers['content-length'], 10);
```

and len became NaN.

So two issues actually: 
1) Bad error handling
2) Missing firmware file.

**Comment by johnnyman727** [comment]
@josser it's working for me now, can you give it another try?

**Comment by josser** [comment]
@johnnyman727 downloading! thank you :dancer:

**Comment by johnnyman727** [comment]
:+1: Thanks for the help!

**Comment by rwaldron** [comment]
@johnnyman727 what was the issue?

**Comment by johnnyman727** [comment]
I had the wrong filename in the tarball that I manually uploaded 😛 

I should really get http://github.com/tessel/t2-release working.
