### ISSUE TITLE
T2 List command fails with controller.js error

### ISSUE THREAD

**Issue by dzeitman** [tessel/t2-cli#647]
t2 list
/usr/local/lib/node_modules/t2-cli/lib/controller.js:41
    .then(() => controller.keyHelper(opts))

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/t2-cli/bin/tessel-2.js:10:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by dzeitman** [comment]
Here's the failing method - please fix.

// Calls any helpers for the get and list codepaths
controller.defaultHelpers = function(opts, next) {
  // First disable output if necessary
  return controller.outputHelper(opts)
    // Then make sure our SSH Key path is updated
    .then(() => controller.keyHelper(opts))
    // before continuing to the next function
    .then(() => next(opts));
};

**Comment by LinusU** [comment]
Which version of Node.js are you running? Minimum required is 4.0.0

**Comment by dzeitman** [comment]
node -v
v0.12.7
