### ISSUE TITLE
Occasional error about not being connected to remote Tessel

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#66]
Every once in a while, I receive an error that a process is attempting to `exec` before the SSH process is opened:
```
INFO Connected over LAN. IP ADDRESS: 192.168.128.149
Unhandled rejection Error: Not connected
    at Client.exec (/Users/Jon/Work/technical/t2-cli/node_modules/ssh2/lib/client.js:544:11)
    at LANConnection.exec (/Users/Jon/Work/technical/t2-cli/lib/lan_connection.js:39:12)
    at stopRunningScript (/Users/Jon/Work/technical/t2-cli/lib/tessel/deploy.js:51:16)
    at Tessel.deployScript (/Users/Jon/Work/technical/t2-cli/lib/tessel/deploy.js:25:3)
    at /Users/Jon/Work/technical/t2-cli/lib/controller.js:173:14
    at tryCatcher (/Users/Jon/Work/technical/t2-cli/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/Jon/Work/technical/t2-cli/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/Jon/Work/technical/t2-cli/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/Jon/Work/technical/t2-cli/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/Jon/Work/technical/t2-cli/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/Users/Jon/Work/technical/t2-cli/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/Users/Jon/Work/technical/t2-cli/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:355:11)
```

**Comment by johnnyman727** [comment]
I believe this occurs when the CLI is told to connect to a device that it is not authenticated on.
