### ISSUE TITLE
Detected CLI crash [Error: Invalid Command received:46] Error: Invalid Command received:46

### ISSUE THREAD

**Issue by ghost** [tessel/t2-cli#762]
Hi. 
I tried T2 with accelerometer and occasionally get this error in the console. It is not reproducible "easily":

```
[... lots of coordinates ...]
x: -0.31 y: -0.32 z: 0.84
x: -0.29 y: -0.30 z: 0ERR! Detected CLI crash [Error: Invalid Command received:46] Error: Invalid Command received:46
    at Parser._parseHeader (/usr/local/lib/node_modules/t2-cli/node_modules/usb-daemon-parser/index.js:243:13)
    at Parser._write (/usr/local/lib/node_modules/t2-cli/node_modules/usb-daemon-parser/index.js:139:34)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Parser.Writable.write (_stream_writable.js:215:11)
    at ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Readable.push (_stream_readable.js:111:10)
    at InEndpoint.<anonymous> (/usr/local/lib/node_modules/t2-cli/lib/usb-connection.js:107:39)
```

node -v v5.10.1 (according to Kelsey this might be the problem. or loose USB cable)

**Comment by johnnyman727** [comment]
Thanks for the report @ghost. I'm not sure what the issue is here but I'll keep it open for some time in case you or anyone else can provide details on how to consistently reproduce.
